/*----------------------------------------------------------------------------*/
/**
* @file		Interrupt_Driver.c
* @brief	割り込みに関するドライバ関数
* @date		24/07/16
* @details	
* @note		
*/
/*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*/
/*インクルードファイル*/
/*----------------------------------------------------------------------------*/
#include <xc.h>
#include "BoardSupportPackage.h"
#include "init_fix.h"
#include "typedef.h"
#include "interrupt_driver.h"
#include "interrupt_user.h"
/*----------------------------------------------------------------------------*/
/*定数定義*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*変数定義*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*プロトタイプ宣言*/
/*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*/
/*
* @fn           vdg_Interrupt_Set_IFS_Register(void)
* @brief        割り込みフラグレジスタを初期化します 
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_Interrupt_Set_IFS_Register(void)
{
    
/*-----------------------------------------------------------------------*/
/* IFS0レジスタ */
/*-----------------------------------------------------------------------*/
	IFS0 = 0x00000000u;
	#ifdef DEF_BITNAME
		IFS0bits.IVTCIF = 0u;
		IFS0bits.CPUFPUIF = 0u;
		IFS0bits.XRAMECCIF = 0u;
		IFS0bits.YRAMECCIF = 0u;
		IFS0bits.PBERRIF = 0u;
		IFS0bits.NVMECCIF = 0u;
		IFS0bits.NVMIF = 0u;
		IFS0bits.NVMCRCIF = 0u;
		IFS0bits.CLKFAILIF = 0u;
		IFS0bits.CLKERRIF = 0u;
		IFS0bits.C1FAILIF = 0u;
		IFS0bits.C1WARNIF = 0u;
		IFS0bits.C1MONIF = 0u;
		IFS0bits.C1RDYIF = 0u;
		IFS0bits.C2FAILIF = 0u;
		IFS0bits.C2WARNIF = 0u;
		IFS0bits.C2MONIF = 0u;
		IFS0bits.C2RDYIF = 0u;
		IFS0bits.C3FAILIF = 0u;
		IFS0bits.C3WARNIF = 0u;
		IFS0bits.C3MONIF = 0u;
		IFS0bits.C3RDYIF = 0u;
		IFS0bits.C4FAILIF = 0u;
		IFS0bits.C4WARNIF = 0u;
		IFS0bits.C4MONIF = 0u;
		IFS0bits.C4RDYIF = 0u;
		IFS0bits.WDTIF = 0u;
	#endif 

/*-----------------------------------------------------------------------*/
/* IFS1レジスタ */
/*-----------------------------------------------------------------------*/
	IFS1 = 0x00000000u;
	#ifdef DEF_BITNAME
		IFS1bits.INT0IF = 0u;
		IFS1bits.INT1IF = 0u;
		IFS1bits.INT2IF = 0u;
		IFS1bits.INT3IF = 0u;
		IFS1bits.INT4IF = 0u;
		IFS1bits.PEVTAIF = 0u;
		IFS1bits.PEVTBIF = 0u;
		IFS1bits.PEVTCIF = 0u;
		IFS1bits.PEVTDIF = 0u;
		IFS1bits.PEVTEIF = 0u;
		IFS1bits.PEVTFIF = 0u;
		IFS1bits.PWM1IF = 0u;
		IFS1bits.PWM2IF = 0u;
		IFS1bits.PWM3IF = 0u;
		IFS1bits.PWM4IF = 0u;
		IFS1bits.T1IF = 0u;
		IFS1bits.CCT1IF = 0u;
		IFS1bits.CCP1IF = 0u;
		IFS1bits.CCT2IF = 0u;
		IFS1bits.CCP2IF = 0u;
		IFS1bits.CCT3IF = 0u;
		IFS1bits.CCP3IF = 0u;
		IFS1bits.CCT4IF = 0u;
		IFS1bits.CCP4IF = 0u;
		IFS1bits.SPI1RXIF = 0u;
	#endif 

/*-----------------------------------------------------------------------*/
/* IFS2レジスタ */
/*-----------------------------------------------------------------------*/
	IFS2 = 0x00000000u;
	#ifdef DEF_BITNAME
		IFS2bits.SPI1TXIF = 0u;
		IFS2bits.SPI1EIF = 0u;
		IFS2bits.SPI2RXIF = 0u;
		IFS2bits.SPI2TXIF = 0u;
		IFS2bits.SPI2EIF = 0u;
		IFS2bits.SPI3RXIF = 0u;
		IFS2bits.SPI3TXIF = 0u;
		IFS2bits.SPI3EIF = 0u;
		IFS2bits.DMA0IF = 0u;
		IFS2bits.DMA1IF = 0u;
		IFS2bits.DMA2IF = 0u;
		IFS2bits.DMA3IF = 0u;
		IFS2bits.CMP1IF = 0u;
		IFS2bits.CMP2IF = 0u;
		IFS2bits.CMP3IF = 0u;
		IFS2bits.I2C1EIF = 0u;
		IFS2bits.I2C1IF = 0u;
		IFS2bits.I2C1RXIF = 0u;
		IFS2bits.I2C1TXIF = 0u;
		IFS2bits.I2C2EIF = 0u;
		IFS2bits.I2C2IF = 0u;
		IFS2bits.I2C2RXIF = 0u;
		IFS2bits.I2C2TXIF = 0u;
		IFS2bits.U1RXIF = 0u;
		IFS2bits.U1TXIF = 0u;
		IFS2bits.U1EIF = 0u;
		IFS2bits.U1EVTIF = 0u;
		IFS2bits.U2RXIF = 0u;
		IFS2bits.U2TXIF = 0u;
		IFS2bits.U2EIF = 0u;
	#endif 

/*-----------------------------------------------------------------------*/
/* IFS3レジスタ */
/*-----------------------------------------------------------------------*/
	IFS3 = 0x00000000u;
	#ifdef DEF_BITNAME
		IFS3bits.U2EVTIF = 0u;
		IFS3bits.U3RXIF = 0u;
		IFS3bits.U3TXIF = 0u;
		IFS3bits.U3EIF = 0u;
		IFS3bits.U3EVTIF = 0u;
		IFS3bits.SENT1IF = 0u;
		IFS3bits.SENT1EIF = 0u;
		IFS3bits.SENT2IF = 0u;
		IFS3bits.SENT2EIF = 0u;
		IFS3bits.DMA4IF = 0u;
		IFS3bits.DMA5IF = 0u;
		IFS3bits.CNAIF = 0u;
		IFS3bits.CNBIF = 0u;
		IFS3bits.CNCIF = 0u;
		IFS3bits.CNDIF = 0u;
		IFS3bits.QEI1IF = 0u;
	#endif 

/*-----------------------------------------------------------------------*/
/* IFS4レジスタ */
/*-----------------------------------------------------------------------*/
	IFS4 = 0x00000000u;
	#ifdef DEF_BITNAME
		IFS4bits.BISS1EIF = 0u;
		IFS4bits.BISS1IF = 0u;
		IFS4bits.CRCIF = 0u;
		IFS4bits.PTGSTEPIF = 0u;
		IFS4bits.PTGWDTIF = 0u;
		IFS4bits.PTG0IF = 0u;
		IFS4bits.PTG1IF = 0u;
		IFS4bits.PTG2IF = 0u;
		IFS4bits.PTG3IF = 0u;
		IFS4bits.AD1CH0IF = 0u;
		IFS4bits.AD1CMP0IF = 0u;
		IFS4bits.AD1CH1IF = 0u;
		IFS4bits.AD1CMP1IF = 0u;
		IFS4bits.AD1CH2IF = 0u;
		IFS4bits.AD1CMP2IF = 0u;
		IFS4bits.AD1CH3IF = 0u;
		IFS4bits.AD1CMP3IF = 0u;
		IFS4bits.AD1CH4IF = 0u;
		IFS4bits.AD1CMP4IF = 0u;
		IFS4bits.AD1CH5IF = 0u;
		IFS4bits.AD1CMP5IF = 0u;
		IFS4bits.AD1CH6IF = 0u;
		IFS4bits.AD1CMP6IF = 0u;
	#endif 

/*-----------------------------------------------------------------------*/
/* IFS5レジスタ */
/*-----------------------------------------------------------------------*/
	IFS5 = 0x00000000u;
	#ifdef DEF_BITNAME
		IFS5bits.AD1CH7IF = 0u;
		IFS5bits.AD1CMP7IF = 0u;
		IFS5bits.AD1CH8IF = 0u;
		IFS5bits.AD1CMP8IF = 0u;
		IFS5bits.AD1CH9IF = 0u;
		IFS5bits.AD1CMP9IF = 0u;
		IFS5bits.AD1CH10IF = 0u;
		IFS5bits.AD1CMP10IF = 0u;
		IFS5bits.AD1CH11IF = 0u;
		IFS5bits.AD1CMP11IF = 0u;
		IFS5bits.AD1CH12IF = 0u;
		IFS5bits.AD1CMP12IF = 0u;
		IFS5bits.AD1CH13IF = 0u;
		IFS5bits.AD1CMP13IF = 0u;
		IFS5bits.AD1CH14IF = 0u;
		IFS5bits.AD1CMP14IF = 0u;
		IFS5bits.AD1CH15IF = 0u;
		IFS5bits.AD1CMP15IF = 0u;
		IFS5bits.AD1CH16IF = 0u;
		IFS5bits.AD1CMP16IF = 0u;
		IFS5bits.AD1CH17IF = 0u;
		IFS5bits.AD1CMP17IF = 0u;
		IFS5bits.AD1CH18IF = 0u;
		IFS5bits.AD1CMP18IF = 0u;
		IFS5bits.AD1CH19IF = 0u;
		IFS5bits.AD1CMP19IF = 0u;
		IFS5bits.AD2CH0IF = 0u;
		IFS5bits.AD2CMP0IF = 0u;
		IFS5bits.AD2CH1IF = 0u;
		IFS5bits.AD2CMP1IF = 0u;
	#endif 

/*-----------------------------------------------------------------------*/
/* IFS6レジスタ */
/*-----------------------------------------------------------------------*/
	IFS6 = 0x00000000u;
	#ifdef DEF_BITNAME
		IFS6bits.AD2CH2IF = 0u;
		IFS6bits.AD2CMP2IF = 0u;
		IFS6bits.AD2CH3IF = 0u;
		IFS6bits.AD2CMP3IF = 0u;
		IFS6bits.AD2CH4IF = 0u;
		IFS6bits.AD2CMP4IF = 0u;
		IFS6bits.AD2CH5IF = 0u;
		IFS6bits.AD2CMP5IF = 0u;
		IFS6bits.AD2CH6IF = 0u;
		IFS6bits.AD2CMP6IF = 0u;
		IFS6bits.AD2CH7IF = 0u;
		IFS6bits.AD2CMP7IF = 0u;
		IFS6bits.AD2CH8IF = 0u;
		IFS6bits.AD2CMP8IF = 0u;
		IFS6bits.AD2CH9IF = 0u;
		IFS6bits.AD2CMP9IF = 0u;
		IFS6bits.AD2CH10IF = 0u;
		IFS6bits.AD2CMP10IF = 0u;
		IFS6bits.AD2CH11IF = 0u;
		IFS6bits.AD2CMP11IF = 0u;
		IFS6bits.AD2CH12IF = 0u;
		IFS6bits.AD2CMP12IF = 0u;
		IFS6bits.AD2CH13IF = 0u;
		IFS6bits.AD2CMP13IF = 0u;
		IFS6bits.AD2CH14IF = 0u;
		IFS6bits.AD2CMP14IF = 0u;
		IFS6bits.AD2CH15IF = 0u;
		IFS6bits.AD2CMP15IF = 0u;
		IFS6bits.AD2CH16IF = 0u;
		IFS6bits.AD2CMP16IF = 0u;
		IFS6bits.AD2CH17IF = 0u;
		IFS6bits.AD2CMP17IF = 0u;
	#endif 

/*-----------------------------------------------------------------------*/
/* IFS7レジスタ */
/*-----------------------------------------------------------------------*/
	IFS7 = 0x00000000u;
	#ifdef DEF_BITNAME
		IFS7bits.AD2CH18IF = 0u;
		IFS7bits.AD2CMP18IF = 0u;
		IFS7bits.AD2CH19IF = 0u;
		IFS7bits.AD2CMP19IF = 0u;
		IFS7bits.CLC1PIF = 0u;
		IFS7bits.CLC1NIF = 0u;
		IFS7bits.CLC2PIF = 0u;
		IFS7bits.CLC2NIF = 0u;
		IFS7bits.CLC3PIF = 0u;
		IFS7bits.CLC3NIF = 0u;
		IFS7bits.CLC4PIF = 0u;
		IFS7bits.CLC4NIF = 0u;
	#endif 

/*-----------------------------------------------------------------------*/
/* IFS8レジスタ */
/*-----------------------------------------------------------------------*/
	IFS8 = 0x00000000u;
	#ifdef DEF_BITNAME
		IFS8bits.IOM1IF = 0u;
		IFS8bits.IOM2IF = 0u;
		IFS8bits.IOM3IF = 0u;
		IFS8bits.IOM4IF = 0u;
	#endif 


}

/*----------------------------------------------------------------------------*/
/*
* @fn           vdg_Interrupt_Set_IEC_Register(void)
* @brief           割り込み有効化レジスタを初期設定します
* @detail
 */
/*----------------------------------------------------------------------------*/
void vdg_Interrupt_Set_IEC_Register(void)
{
    
/*-----------------------------------------------------------------------*/
/* IEC0レジスタ */
/*-----------------------------------------------------------------------*/
	IEC0 =	IRPT_USER_ENABLE_CPUFPUIE  << _IEC0_CPUFPUIE_POSITION | 
			IRPT_USER_ENABLE_XRAMECCIE  << _IEC0_XRAMECCIE_POSITION | 
			IRPT_USER_ENABLE_YRAMECCIE  << _IEC0_YRAMECCIE_POSITION | 
			IRPT_USER_ENABLE_PBERRIE  << _IEC0_PBERRIE_POSITION | 
			IRPT_USER_ENABLE_NVMECCIE  << _IEC0_NVMECCIE_POSITION | 
			IRPT_USER_ENABLE_NVMIE  << _IEC0_NVMIE_POSITION | 
			IRPT_USER_ENABLE_NVMCRCIE  << _IEC0_NVMCRCIE_POSITION | 
			IRPT_USER_ENABLE_CLKFAILIE  << _IEC0_CLKFAILIE_POSITION | 
			IRPT_USER_ENABLE_CLKERRIE  << _IEC0_CLKERRIE_POSITION | 
			IRPT_USER_ENABLE_C1FAILIE  << _IEC0_C1FAILIE_POSITION | 
			IRPT_USER_ENABLE_C1WARNIE  << _IEC0_C1WARNIE_POSITION | 
			IRPT_USER_ENABLE_C1MONIE  << _IEC0_C1MONIE_POSITION | 
			IRPT_USER_ENABLE_C1RDYIE  << _IEC0_C1RDYIE_POSITION | 
			IRPT_USER_ENABLE_C2FAILIE  << _IEC0_C2FAILIE_POSITION | 
			IRPT_USER_ENABLE_C2WARNIE  << _IEC0_C2WARNIE_POSITION | 
			IRPT_USER_ENABLE_C2MONIE  << _IEC0_C2MONIE_POSITION | 
			IRPT_USER_ENABLE_C2RDYIE  << _IEC0_C2RDYIE_POSITION | 
			IRPT_USER_ENABLE_C3FAILIE  << _IEC0_C3FAILIE_POSITION | 
			IRPT_USER_ENABLE_C3WARNIE  << _IEC0_C3WARNIE_POSITION | 
			IRPT_USER_ENABLE_C3MONIE  << _IEC0_C3MONIE_POSITION | 
			IRPT_USER_ENABLE_C3RDYIE  << _IEC0_C3RDYIE_POSITION | 
			IRPT_USER_ENABLE_C4FAILIE  << _IEC0_C4FAILIE_POSITION | 
			IRPT_USER_ENABLE_C4WARNIE  << _IEC0_C4WARNIE_POSITION | 
			IRPT_USER_ENABLE_C4MONIE  << _IEC0_C4MONIE_POSITION | 
			IRPT_USER_ENABLE_C4RDYIE  << _IEC0_C4RDYIE_POSITION | 
			IRPT_USER_ENABLE_WDTIE  << _IEC0_WDTIE_POSITION ;
#ifdef DEF_BITNAME
	IEC0bits.CPUFPUIE = IRPT_USER_ENABLE_CPUFPUIE ;
	IEC0bits.XRAMECCIE = IRPT_USER_ENABLE_XRAMECCIE ;
	IEC0bits.YRAMECCIE = IRPT_USER_ENABLE_YRAMECCIE ;
	IEC0bits.PBERRIE = IRPT_USER_ENABLE_PBERRIE ;
	IEC0bits.NVMECCIE = IRPT_USER_ENABLE_NVMECCIE ;
	IEC0bits.NVMIE = IRPT_USER_ENABLE_NVMIE ;
	IEC0bits.NVMCRCIE = IRPT_USER_ENABLE_NVMCRCIE ;
	IEC0bits.CLKFAILIE = IRPT_USER_ENABLE_CLKFAILIE ;
	IEC0bits.CLKERRIE = IRPT_USER_ENABLE_CLKERRIE ;
	IEC0bits.C1FAILIE = IRPT_USER_ENABLE_C1FAILIE ;
	IEC0bits.C1WARNIE = IRPT_USER_ENABLE_C1WARNIE ;
	IEC0bits.C1MONIE = IRPT_USER_ENABLE_C1MONIE ;
	IEC0bits.C1RDYIE = IRPT_USER_ENABLE_C1RDYIE ;
	IEC0bits.C2FAILIE = IRPT_USER_ENABLE_C2FAILIE ;
	IEC0bits.C2WARNIE = IRPT_USER_ENABLE_C2WARNIE ;
	IEC0bits.C2MONIE = IRPT_USER_ENABLE_C2MONIE ;
	IEC0bits.C2RDYIE = IRPT_USER_ENABLE_C2RDYIE ;
	IEC0bits.C3FAILIE = IRPT_USER_ENABLE_C3FAILIE ;
	IEC0bits.C3WARNIE = IRPT_USER_ENABLE_C3WARNIE ;
	IEC0bits.C3MONIE = IRPT_USER_ENABLE_C3MONIE ;
	IEC0bits.C3RDYIE = IRPT_USER_ENABLE_C3RDYIE ;
	IEC0bits.C4FAILIE = IRPT_USER_ENABLE_C4FAILIE ;
	IEC0bits.C4WARNIE = IRPT_USER_ENABLE_C4WARNIE ;
	IEC0bits.C4MONIE = IRPT_USER_ENABLE_C4MONIE ;
	IEC0bits.C4RDYIE = IRPT_USER_ENABLE_C4RDYIE ;
	IEC0bits.WDTIE = IRPT_USER_ENABLE_WDTIE ;
#endif 

/*-----------------------------------------------------------------------*/
/* IEC1レジスタ */
/*-----------------------------------------------------------------------*/
	IEC1 =	IRPT_USER_ENABLE_INT0IE  << _IEC1_INT0IE_POSITION | 
			IRPT_USER_ENABLE_INT1IE  << _IEC1_INT1IE_POSITION | 
			IRPT_USER_ENABLE_INT2IE  << _IEC1_INT2IE_POSITION | 
			IRPT_USER_ENABLE_INT3IE  << _IEC1_INT3IE_POSITION | 
			IRPT_USER_ENABLE_INT4IE  << _IEC1_INT4IE_POSITION | 
			IRPT_USER_ENABLE_PEVTAIE  << _IEC1_PEVTAIE_POSITION | 
			IRPT_USER_ENABLE_PEVTBIE  << _IEC1_PEVTBIE_POSITION | 
			IRPT_USER_ENABLE_PEVTCIE  << _IEC1_PEVTCIE_POSITION | 
			IRPT_USER_ENABLE_PEVTDIE  << _IEC1_PEVTDIE_POSITION | 
			IRPT_USER_ENABLE_PEVTEIE  << _IEC1_PEVTEIE_POSITION | 
			IRPT_USER_ENABLE_PEVTFIE  << _IEC1_PEVTFIE_POSITION | 
			IRPT_USER_ENABLE_PWM1IE  << _IEC1_PWM1IE_POSITION | 
			IRPT_USER_ENABLE_PWM2IE  << _IEC1_PWM2IE_POSITION | 
			IRPT_USER_ENABLE_PWM3IE  << _IEC1_PWM3IE_POSITION | 
			IRPT_USER_ENABLE_PWM4IE  << _IEC1_PWM4IE_POSITION | 
			IRPT_USER_ENABLE_T1IE  << _IEC1_T1IE_POSITION | 
			IRPT_USER_ENABLE_CCT1IE  << _IEC1_CCT1IE_POSITION | 
			IRPT_USER_ENABLE_CCP1IE  << _IEC1_CCP1IE_POSITION | 
			IRPT_USER_ENABLE_CCT2IE  << _IEC1_CCT2IE_POSITION | 
			IRPT_USER_ENABLE_CCP2IE  << _IEC1_CCP2IE_POSITION | 
			IRPT_USER_ENABLE_CCT3IE  << _IEC1_CCT3IE_POSITION | 
			IRPT_USER_ENABLE_CCP3IE  << _IEC1_CCP3IE_POSITION | 
			IRPT_USER_ENABLE_CCT4IE  << _IEC1_CCT4IE_POSITION | 
			IRPT_USER_ENABLE_CCP4IE  << _IEC1_CCP4IE_POSITION | 
			IRPT_USER_ENABLE_SPI1RXIE  << _IEC1_SPI1RXIE_POSITION ;
#ifdef DEF_BITNAME
	IEC1bits.INT0IE = IRPT_USER_ENABLE_INT0IE ;
	IEC1bits.INT1IE = IRPT_USER_ENABLE_INT1IE ;
	IEC1bits.INT2IE = IRPT_USER_ENABLE_INT2IE ;
	IEC1bits.INT3IE = IRPT_USER_ENABLE_INT3IE ;
	IEC1bits.INT4IE = IRPT_USER_ENABLE_INT4IE ;
	IEC1bits.PEVTAIE = IRPT_USER_ENABLE_PEVTAIE ;
	IEC1bits.PEVTBIE = IRPT_USER_ENABLE_PEVTBIE ;
	IEC1bits.PEVTCIE = IRPT_USER_ENABLE_PEVTCIE ;
	IEC1bits.PEVTDIE = IRPT_USER_ENABLE_PEVTDIE ;
	IEC1bits.PEVTEIE = IRPT_USER_ENABLE_PEVTEIE ;
	IEC1bits.PEVTFIE = IRPT_USER_ENABLE_PEVTFIE ;
	IEC1bits.PWM1IE = IRPT_USER_ENABLE_PWM1IE ;
	IEC1bits.PWM2IE = IRPT_USER_ENABLE_PWM2IE ;
	IEC1bits.PWM3IE = IRPT_USER_ENABLE_PWM3IE ;
	IEC1bits.PWM4IE = IRPT_USER_ENABLE_PWM4IE ;
	IEC1bits.T1IE = IRPT_USER_ENABLE_T1IE ;
	IEC1bits.CCT1IE = IRPT_USER_ENABLE_CCT1IE ;
	IEC1bits.CCP1IE = IRPT_USER_ENABLE_CCP1IE ;
	IEC1bits.CCT2IE = IRPT_USER_ENABLE_CCT2IE ;
	IEC1bits.CCP2IE = IRPT_USER_ENABLE_CCP2IE ;
	IEC1bits.CCT3IE = IRPT_USER_ENABLE_CCT3IE ;
	IEC1bits.CCP3IE = IRPT_USER_ENABLE_CCP3IE ;
	IEC1bits.CCT4IE = IRPT_USER_ENABLE_CCT4IE ;
	IEC1bits.CCP4IE = IRPT_USER_ENABLE_CCP4IE ;
	IEC1bits.SPI1RXIE = IRPT_USER_ENABLE_SPI1RXIE ;
#endif 

/*-----------------------------------------------------------------------*/
/* IEC2レジスタ */
/*-----------------------------------------------------------------------*/
	IEC2 =	IRPT_USER_ENABLE_SPI1TXIE  << _IEC2_SPI1TXIE_POSITION | 
			IRPT_USER_ENABLE_SPI1EIE  << _IEC2_SPI1EIE_POSITION | 
			IRPT_USER_ENABLE_SPI2RXIE  << _IEC2_SPI2RXIE_POSITION | 
			IRPT_USER_ENABLE_SPI2TXIE  << _IEC2_SPI2TXIE_POSITION | 
			IRPT_USER_ENABLE_SPI2EIE  << _IEC2_SPI2EIE_POSITION | 
			IRPT_USER_ENABLE_SPI3RXIE  << _IEC2_SPI3RXIE_POSITION | 
			IRPT_USER_ENABLE_SPI3TXIE  << _IEC2_SPI3TXIE_POSITION | 
			IRPT_USER_ENABLE_SPI3EIE  << _IEC2_SPI3EIE_POSITION | 
			IRPT_USER_ENABLE_DMA0IE  << _IEC2_DMA0IE_POSITION | 
			IRPT_USER_ENABLE_DMA1IE  << _IEC2_DMA1IE_POSITION | 
			IRPT_USER_ENABLE_DMA2IE  << _IEC2_DMA2IE_POSITION | 
			IRPT_USER_ENABLE_DMA3IE  << _IEC2_DMA3IE_POSITION | 
			IRPT_USER_ENABLE_CMP1IE  << _IEC2_CMP1IE_POSITION | 
			IRPT_USER_ENABLE_CMP2IE  << _IEC2_CMP2IE_POSITION | 
			IRPT_USER_ENABLE_CMP3IE  << _IEC2_CMP3IE_POSITION | 
			IRPT_USER_ENABLE_I2C1EIE  << _IEC2_I2C1EIE_POSITION | 
			IRPT_USER_ENABLE_I2C1IE  << _IEC2_I2C1IE_POSITION | 
			IRPT_USER_ENABLE_I2C1RXIE  << _IEC2_I2C1RXIE_POSITION | 
			IRPT_USER_ENABLE_I2C1TXIE  << _IEC2_I2C1TXIE_POSITION | 
			IRPT_USER_ENABLE_I2C2EIE  << _IEC2_I2C2EIE_POSITION | 
			IRPT_USER_ENABLE_I2C2IE  << _IEC2_I2C2IE_POSITION | 
			IRPT_USER_ENABLE_I2C2RXIE  << _IEC2_I2C2RXIE_POSITION | 
			IRPT_USER_ENABLE_I2C2TXIE  << _IEC2_I2C2TXIE_POSITION | 
			IRPT_USER_ENABLE_U1RXIE  << _IEC2_U1RXIE_POSITION | 
			IRPT_USER_ENABLE_U1TXIE  << _IEC2_U1TXIE_POSITION | 
			IRPT_USER_ENABLE_U1EIE  << _IEC2_U1EIE_POSITION | 
			IRPT_USER_ENABLE_U1EVTIE  << _IEC2_U1EVTIE_POSITION | 
			IRPT_USER_ENABLE_U2RXIE  << _IEC2_U2RXIE_POSITION | 
			IRPT_USER_ENABLE_U2TXIE  << _IEC2_U2TXIE_POSITION | 
			IRPT_USER_ENABLE_U2EIE  << _IEC2_U2EIE_POSITION ;
#ifdef DEF_BITNAME
	IEC2bits.SPI1TXIE = IRPT_USER_ENABLE_SPI1TXIE ;
	IEC2bits.SPI1EIE = IRPT_USER_ENABLE_SPI1EIE ;
	IEC2bits.SPI2RXIE = IRPT_USER_ENABLE_SPI2RXIE ;
	IEC2bits.SPI2TXIE = IRPT_USER_ENABLE_SPI2TXIE ;
	IEC2bits.SPI2EIE = IRPT_USER_ENABLE_SPI2EIE ;
	IEC2bits.SPI3RXIE = IRPT_USER_ENABLE_SPI3RXIE ;
	IEC2bits.SPI3TXIE = IRPT_USER_ENABLE_SPI3TXIE ;
	IEC2bits.SPI3EIE = IRPT_USER_ENABLE_SPI3EIE ;
	IEC2bits.DMA0IE = IRPT_USER_ENABLE_DMA0IE ;
	IEC2bits.DMA1IE = IRPT_USER_ENABLE_DMA1IE ;
	IEC2bits.DMA2IE = IRPT_USER_ENABLE_DMA2IE ;
	IEC2bits.DMA3IE = IRPT_USER_ENABLE_DMA3IE ;
	IEC2bits.CMP1IE = IRPT_USER_ENABLE_CMP1IE ;
	IEC2bits.CMP2IE = IRPT_USER_ENABLE_CMP2IE ;
	IEC2bits.CMP3IE = IRPT_USER_ENABLE_CMP3IE ;
	IEC2bits.I2C1EIE = IRPT_USER_ENABLE_I2C1EIE ;
	IEC2bits.I2C1IE = IRPT_USER_ENABLE_I2C1IE ;
	IEC2bits.I2C1RXIE = IRPT_USER_ENABLE_I2C1RXIE ;
	IEC2bits.I2C1TXIE = IRPT_USER_ENABLE_I2C1TXIE ;
	IEC2bits.I2C2EIE = IRPT_USER_ENABLE_I2C2EIE ;
	IEC2bits.I2C2IE = IRPT_USER_ENABLE_I2C2IE ;
	IEC2bits.I2C2RXIE = IRPT_USER_ENABLE_I2C2RXIE ;
	IEC2bits.I2C2TXIE = IRPT_USER_ENABLE_I2C2TXIE ;
	IEC2bits.U1RXIE = IRPT_USER_ENABLE_U1RXIE ;
	IEC2bits.U1TXIE = IRPT_USER_ENABLE_U1TXIE ;
	IEC2bits.U1EIE = IRPT_USER_ENABLE_U1EIE ;
	IEC2bits.U1EVTIE = IRPT_USER_ENABLE_U1EVTIE ;
	IEC2bits.U2RXIE = IRPT_USER_ENABLE_U2RXIE ;
	IEC2bits.U2TXIE = IRPT_USER_ENABLE_U2TXIE ;
	IEC2bits.U2EIE = IRPT_USER_ENABLE_U2EIE ;
#endif 

/*-----------------------------------------------------------------------*/
/* IEC3レジスタ */
/*-----------------------------------------------------------------------*/
	IEC3 =	IRPT_USER_ENABLE_U2EVTIE  << _IEC3_U2EVTIE_POSITION | 
			IRPT_USER_ENABLE_U3RXIE  << _IEC3_U3RXIE_POSITION | 
			IRPT_USER_ENABLE_U3TXIE  << _IEC3_U3TXIE_POSITION | 
			IRPT_USER_ENABLE_U3EIE  << _IEC3_U3EIE_POSITION | 
			IRPT_USER_ENABLE_U3EVTIE  << _IEC3_U3EVTIE_POSITION | 
			IRPT_USER_ENABLE_SENT1IE  << _IEC3_SENT1IE_POSITION | 
			IRPT_USER_ENABLE_SENT1EIE  << _IEC3_SENT1EIE_POSITION | 
			IRPT_USER_ENABLE_SENT2IE  << _IEC3_SENT2IE_POSITION | 
			IRPT_USER_ENABLE_SENT2EIE  << _IEC3_SENT2EIE_POSITION | 
			IRPT_USER_ENABLE_DMA4IE  << _IEC3_DMA4IE_POSITION | 
			IRPT_USER_ENABLE_DMA5IE  << _IEC3_DMA5IE_POSITION | 
			IRPT_USER_ENABLE_CNAIE  << _IEC3_CNAIE_POSITION | 
			IRPT_USER_ENABLE_CNBIE  << _IEC3_CNBIE_POSITION | 
			IRPT_USER_ENABLE_CNCIE  << _IEC3_CNCIE_POSITION | 
			IRPT_USER_ENABLE_CNDIE  << _IEC3_CNDIE_POSITION | 
			IRPT_USER_ENABLE_QEI1IE  << _IEC3_QEI1IE_POSITION ;
#ifdef DEF_BITNAME
	IEC3bits.U2EVTIE = IRPT_USER_ENABLE_U2EVTIE ;
	IEC3bits.U3RXIE = IRPT_USER_ENABLE_U3RXIE ;
	IEC3bits.U3TXIE = IRPT_USER_ENABLE_U3TXIE ;
	IEC3bits.U3EIE = IRPT_USER_ENABLE_U3EIE ;
	IEC3bits.U3EVTIE = IRPT_USER_ENABLE_U3EVTIE ;
	IEC3bits.SENT1IE = IRPT_USER_ENABLE_SENT1IE ;
	IEC3bits.SENT1EIE = IRPT_USER_ENABLE_SENT1EIE ;
	IEC3bits.SENT2IE = IRPT_USER_ENABLE_SENT2IE ;
	IEC3bits.SENT2EIE = IRPT_USER_ENABLE_SENT2EIE ;
	IEC3bits.DMA4IE = IRPT_USER_ENABLE_DMA4IE ;
	IEC3bits.DMA5IE = IRPT_USER_ENABLE_DMA5IE ;
	IEC3bits.CNAIE = IRPT_USER_ENABLE_CNAIE ;
	IEC3bits.CNBIE = IRPT_USER_ENABLE_CNBIE ;
	IEC3bits.CNCIE = IRPT_USER_ENABLE_CNCIE ;
	IEC3bits.CNDIE = IRPT_USER_ENABLE_CNDIE ;
	IEC3bits.QEI1IE = IRPT_USER_ENABLE_QEI1IE ;
#endif 

/*-----------------------------------------------------------------------*/
/* IEC4レジスタ */
/*-----------------------------------------------------------------------*/
	IEC4 =	IRPT_USER_ENABLE_BISS1EIE  << _IEC4_BISS1EIE_POSITION | 
			IRPT_USER_ENABLE_BISS1IE  << _IEC4_BISS1IE_POSITION | 
			IRPT_USER_ENABLE_CRCIE  << _IEC4_CRCIE_POSITION | 
			IRPT_USER_ENABLE_PTGSTEPIE  << _IEC4_PTGSTEPIE_POSITION | 
			IRPT_USER_ENABLE_PTGWDTIE  << _IEC4_PTGWDTIE_POSITION | 
			IRPT_USER_ENABLE_PTG0IE  << _IEC4_PTG0IE_POSITION | 
			IRPT_USER_ENABLE_PTG1IE  << _IEC4_PTG1IE_POSITION | 
			IRPT_USER_ENABLE_PTG2IE  << _IEC4_PTG2IE_POSITION | 
			IRPT_USER_ENABLE_PTG3IE  << _IEC4_PTG3IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH0IE  << _IEC4_AD1CH0IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP0IE  << _IEC4_AD1CMP0IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH1IE  << _IEC4_AD1CH1IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP1IE  << _IEC4_AD1CMP1IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH2IE  << _IEC4_AD1CH2IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP2IE  << _IEC4_AD1CMP2IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH3IE  << _IEC4_AD1CH3IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP3IE  << _IEC4_AD1CMP3IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH4IE  << _IEC4_AD1CH4IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP4IE  << _IEC4_AD1CMP4IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH5IE  << _IEC4_AD1CH5IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP5IE  << _IEC4_AD1CMP5IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH6IE  << _IEC4_AD1CH6IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP6IE  << _IEC4_AD1CMP6IE_POSITION ;
#ifdef DEF_BITNAME
	IEC4bits.BISS1EIE = IRPT_USER_ENABLE_BISS1EIE ;
	IEC4bits.BISS1IE = IRPT_USER_ENABLE_BISS1IE ;
	IEC4bits.CRCIE = IRPT_USER_ENABLE_CRCIE ;
	IEC4bits.PTGSTEPIE = IRPT_USER_ENABLE_PTGSTEPIE ;
	IEC4bits.PTGWDTIE = IRPT_USER_ENABLE_PTGWDTIE ;
	IEC4bits.PTG0IE = IRPT_USER_ENABLE_PTG0IE ;
	IEC4bits.PTG1IE = IRPT_USER_ENABLE_PTG1IE ;
	IEC4bits.PTG2IE = IRPT_USER_ENABLE_PTG2IE ;
	IEC4bits.PTG3IE = IRPT_USER_ENABLE_PTG3IE ;
	IEC4bits.AD1CH0IE = IRPT_USER_ENABLE_AD1CH0IE ;
	IEC4bits.AD1CMP0IE = IRPT_USER_ENABLE_AD1CMP0IE ;
	IEC4bits.AD1CH1IE = IRPT_USER_ENABLE_AD1CH1IE ;
	IEC4bits.AD1CMP1IE = IRPT_USER_ENABLE_AD1CMP1IE ;
	IEC4bits.AD1CH2IE = IRPT_USER_ENABLE_AD1CH2IE ;
	IEC4bits.AD1CMP2IE = IRPT_USER_ENABLE_AD1CMP2IE ;
	IEC4bits.AD1CH3IE = IRPT_USER_ENABLE_AD1CH3IE ;
	IEC4bits.AD1CMP3IE = IRPT_USER_ENABLE_AD1CMP3IE ;
	IEC4bits.AD1CH4IE = IRPT_USER_ENABLE_AD1CH4IE ;
	IEC4bits.AD1CMP4IE = IRPT_USER_ENABLE_AD1CMP4IE ;
	IEC4bits.AD1CH5IE = IRPT_USER_ENABLE_AD1CH5IE ;
	IEC4bits.AD1CMP5IE = IRPT_USER_ENABLE_AD1CMP5IE ;
	IEC4bits.AD1CH6IE = IRPT_USER_ENABLE_AD1CH6IE ;
	IEC4bits.AD1CMP6IE = IRPT_USER_ENABLE_AD1CMP6IE ;
#endif 

/*-----------------------------------------------------------------------*/
/* IEC5レジスタ */
/*-----------------------------------------------------------------------*/
	IEC5 =	IRPT_USER_ENABLE_AD1CH7IE  << _IEC5_AD1CH7IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP7IE  << _IEC5_AD1CMP7IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH8IE  << _IEC5_AD1CH8IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP8IE  << _IEC5_AD1CMP8IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH9IE  << _IEC5_AD1CH9IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP9IE  << _IEC5_AD1CMP9IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH10IE  << _IEC5_AD1CH10IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP10IE  << _IEC5_AD1CMP10IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH11IE  << _IEC5_AD1CH11IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP11IE  << _IEC5_AD1CMP11IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH12IE  << _IEC5_AD1CH12IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP12IE  << _IEC5_AD1CMP12IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH13IE  << _IEC5_AD1CH13IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP13IE  << _IEC5_AD1CMP13IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH14IE  << _IEC5_AD1CH14IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP14IE  << _IEC5_AD1CMP14IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH15IE  << _IEC5_AD1CH15IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP15IE  << _IEC5_AD1CMP15IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH16IE  << _IEC5_AD1CH16IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP16IE  << _IEC5_AD1CMP16IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH17IE  << _IEC5_AD1CH17IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP17IE  << _IEC5_AD1CMP17IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH18IE  << _IEC5_AD1CH18IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP18IE  << _IEC5_AD1CMP18IE_POSITION | 
			IRPT_USER_ENABLE_AD1CH19IE  << _IEC5_AD1CH19IE_POSITION | 
			IRPT_USER_ENABLE_AD1CMP19IE  << _IEC5_AD1CMP19IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH0IE  << _IEC5_AD2CH0IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP0IE  << _IEC5_AD2CMP0IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH1IE  << _IEC5_AD2CH1IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP1IE  << _IEC5_AD2CMP1IE_POSITION ;
#ifdef DEF_BITNAME
	IEC5bits.AD1CH7IE = IRPT_USER_ENABLE_AD1CH7IE ;
	IEC5bits.AD1CMP7IE = IRPT_USER_ENABLE_AD1CMP7IE ;
	IEC5bits.AD1CH8IE = IRPT_USER_ENABLE_AD1CH8IE ;
	IEC5bits.AD1CMP8IE = IRPT_USER_ENABLE_AD1CMP8IE ;
	IEC5bits.AD1CH9IE = IRPT_USER_ENABLE_AD1CH9IE ;
	IEC5bits.AD1CMP9IE = IRPT_USER_ENABLE_AD1CMP9IE ;
	IEC5bits.AD1CH10IE = IRPT_USER_ENABLE_AD1CH10IE ;
	IEC5bits.AD1CMP10IE = IRPT_USER_ENABLE_AD1CMP10IE ;
	IEC5bits.AD1CH11IE = IRPT_USER_ENABLE_AD1CH11IE ;
	IEC5bits.AD1CMP11IE = IRPT_USER_ENABLE_AD1CMP11IE ;
	IEC5bits.AD1CH12IE = IRPT_USER_ENABLE_AD1CH12IE ;
	IEC5bits.AD1CMP12IE = IRPT_USER_ENABLE_AD1CMP12IE ;
	IEC5bits.AD1CH13IE = IRPT_USER_ENABLE_AD1CH13IE ;
	IEC5bits.AD1CMP13IE = IRPT_USER_ENABLE_AD1CMP13IE ;
	IEC5bits.AD1CH14IE = IRPT_USER_ENABLE_AD1CH14IE ;
	IEC5bits.AD1CMP14IE = IRPT_USER_ENABLE_AD1CMP14IE ;
	IEC5bits.AD1CH15IE = IRPT_USER_ENABLE_AD1CH15IE ;
	IEC5bits.AD1CMP15IE = IRPT_USER_ENABLE_AD1CMP15IE ;
	IEC5bits.AD1CH16IE = IRPT_USER_ENABLE_AD1CH16IE ;
	IEC5bits.AD1CMP16IE = IRPT_USER_ENABLE_AD1CMP16IE ;
	IEC5bits.AD1CH17IE = IRPT_USER_ENABLE_AD1CH17IE ;
	IEC5bits.AD1CMP17IE = IRPT_USER_ENABLE_AD1CMP17IE ;
	IEC5bits.AD1CH18IE = IRPT_USER_ENABLE_AD1CH18IE ;
	IEC5bits.AD1CMP18IE = IRPT_USER_ENABLE_AD1CMP18IE ;
	IEC5bits.AD1CH19IE = IRPT_USER_ENABLE_AD1CH19IE ;
	IEC5bits.AD1CMP19IE = IRPT_USER_ENABLE_AD1CMP19IE ;
	IEC5bits.AD2CH0IE = IRPT_USER_ENABLE_AD2CH0IE ;
	IEC5bits.AD2CMP0IE = IRPT_USER_ENABLE_AD2CMP0IE ;
	IEC5bits.AD2CH1IE = IRPT_USER_ENABLE_AD2CH1IE ;
	IEC5bits.AD2CMP1IE = IRPT_USER_ENABLE_AD2CMP1IE ;
#endif 

/*-----------------------------------------------------------------------*/
/* IEC6レジスタ */
/*-----------------------------------------------------------------------*/
	IEC6 =	IRPT_USER_ENABLE_AD2CH2IE  << _IEC6_AD2CH2IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP2IE  << _IEC6_AD2CMP2IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH3IE  << _IEC6_AD2CH3IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP3IE  << _IEC6_AD2CMP3IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH4IE  << _IEC6_AD2CH4IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP4IE  << _IEC6_AD2CMP4IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH5IE  << _IEC6_AD2CH5IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP5IE  << _IEC6_AD2CMP5IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH6IE  << _IEC6_AD2CH6IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP6IE  << _IEC6_AD2CMP6IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH7IE  << _IEC6_AD2CH7IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP7IE  << _IEC6_AD2CMP7IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH8IE  << _IEC6_AD2CH8IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP8IE  << _IEC6_AD2CMP8IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH9IE  << _IEC6_AD2CH9IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP9IE  << _IEC6_AD2CMP9IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH10IE  << _IEC6_AD2CH10IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP10IE  << _IEC6_AD2CMP10IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH11IE  << _IEC6_AD2CH11IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP11IE  << _IEC6_AD2CMP11IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH12IE  << _IEC6_AD2CH12IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP12IE  << _IEC6_AD2CMP12IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH13IE  << _IEC6_AD2CH13IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP13IE  << _IEC6_AD2CMP13IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH14IE  << _IEC6_AD2CH14IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP14IE  << _IEC6_AD2CMP14IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH15IE  << _IEC6_AD2CH15IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP15IE  << _IEC6_AD2CMP15IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH16IE  << _IEC6_AD2CH16IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP16IE  << _IEC6_AD2CMP16IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH17IE  << _IEC6_AD2CH17IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP17IE  << _IEC6_AD2CMP17IE_POSITION ;
#ifdef DEF_BITNAME
	IEC6bits.AD2CH2IE = IRPT_USER_ENABLE_AD2CH2IE ;
	IEC6bits.AD2CMP2IE = IRPT_USER_ENABLE_AD2CMP2IE ;
	IEC6bits.AD2CH3IE = IRPT_USER_ENABLE_AD2CH3IE ;
	IEC6bits.AD2CMP3IE = IRPT_USER_ENABLE_AD2CMP3IE ;
	IEC6bits.AD2CH4IE = IRPT_USER_ENABLE_AD2CH4IE ;
	IEC6bits.AD2CMP4IE = IRPT_USER_ENABLE_AD2CMP4IE ;
	IEC6bits.AD2CH5IE = IRPT_USER_ENABLE_AD2CH5IE ;
	IEC6bits.AD2CMP5IE = IRPT_USER_ENABLE_AD2CMP5IE ;
	IEC6bits.AD2CH6IE = IRPT_USER_ENABLE_AD2CH6IE ;
	IEC6bits.AD2CMP6IE = IRPT_USER_ENABLE_AD2CMP6IE ;
	IEC6bits.AD2CH7IE = IRPT_USER_ENABLE_AD2CH7IE ;
	IEC6bits.AD2CMP7IE = IRPT_USER_ENABLE_AD2CMP7IE ;
	IEC6bits.AD2CH8IE = IRPT_USER_ENABLE_AD2CH8IE ;
	IEC6bits.AD2CMP8IE = IRPT_USER_ENABLE_AD2CMP8IE ;
	IEC6bits.AD2CH9IE = IRPT_USER_ENABLE_AD2CH9IE ;
	IEC6bits.AD2CMP9IE = IRPT_USER_ENABLE_AD2CMP9IE ;
	IEC6bits.AD2CH10IE = IRPT_USER_ENABLE_AD2CH10IE ;
	IEC6bits.AD2CMP10IE = IRPT_USER_ENABLE_AD2CMP10IE ;
	IEC6bits.AD2CH11IE = IRPT_USER_ENABLE_AD2CH11IE ;
	IEC6bits.AD2CMP11IE = IRPT_USER_ENABLE_AD2CMP11IE ;
	IEC6bits.AD2CH12IE = IRPT_USER_ENABLE_AD2CH12IE ;
	IEC6bits.AD2CMP12IE = IRPT_USER_ENABLE_AD2CMP12IE ;
	IEC6bits.AD2CH13IE = IRPT_USER_ENABLE_AD2CH13IE ;
	IEC6bits.AD2CMP13IE = IRPT_USER_ENABLE_AD2CMP13IE ;
	IEC6bits.AD2CH14IE = IRPT_USER_ENABLE_AD2CH14IE ;
	IEC6bits.AD2CMP14IE = IRPT_USER_ENABLE_AD2CMP14IE ;
	IEC6bits.AD2CH15IE = IRPT_USER_ENABLE_AD2CH15IE ;
	IEC6bits.AD2CMP15IE = IRPT_USER_ENABLE_AD2CMP15IE ;
	IEC6bits.AD2CH16IE = IRPT_USER_ENABLE_AD2CH16IE ;
	IEC6bits.AD2CMP16IE = IRPT_USER_ENABLE_AD2CMP16IE ;
	IEC6bits.AD2CH17IE = IRPT_USER_ENABLE_AD2CH17IE ;
	IEC6bits.AD2CMP17IE = IRPT_USER_ENABLE_AD2CMP17IE ;
#endif 

/*-----------------------------------------------------------------------*/
/* IEC7レジスタ */
/*-----------------------------------------------------------------------*/
	IEC7 =	 IRPT_USER_ENABLE_AD2CH18IE  << _IEC7_AD2CH18IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP18IE  << _IEC7_AD2CMP18IE_POSITION | 
			IRPT_USER_ENABLE_AD2CH19IE  << _IEC7_AD2CH19IE_POSITION | 
			IRPT_USER_ENABLE_AD2CMP19IE  << _IEC7_AD2CMP19IE_POSITION | 
			IRPT_USER_ENABLE_CLC1PIE  << _IEC7_CLC1PIE_POSITION | 
			IRPT_USER_ENABLE_CLC1NIE  << _IEC7_CLC1NIE_POSITION | 
			IRPT_USER_ENABLE_CLC2PIE  << _IEC7_CLC2PIE_POSITION | 
			IRPT_USER_ENABLE_CLC2NIE  << _IEC7_CLC2NIE_POSITION | 
			IRPT_USER_ENABLE_CLC3PIE  << _IEC7_CLC3PIE_POSITION | 
			IRPT_USER_ENABLE_CLC3NIE  << _IEC7_CLC3NIE_POSITION | 
			IRPT_USER_ENABLE_CLC4PIE  << _IEC7_CLC4PIE_POSITION | 
			IRPT_USER_ENABLE_CLC4NIE  << _IEC7_CLC4NIE_POSITION ;
#ifdef DEF_BITNAME
	IEC7bits.AD2CH18IE = IRPT_USER_ENABLE_AD2CH18IE ;
	IEC7bits.AD2CMP18IE = IRPT_USER_ENABLE_AD2CMP18IE ;
	IEC7bits.AD2CH19IE = IRPT_USER_ENABLE_AD2CH19IE ;
	IEC7bits.AD2CMP19IE = IRPT_USER_ENABLE_AD2CMP19IE ;
	IEC7bits.CLC1PIE = IRPT_USER_ENABLE_CLC1PIE ;
	IEC7bits.CLC1NIE = IRPT_USER_ENABLE_CLC1NIE ;
	IEC7bits.CLC2PIE = IRPT_USER_ENABLE_CLC2PIE ;
	IEC7bits.CLC2NIE = IRPT_USER_ENABLE_CLC2NIE ;
	IEC7bits.CLC3PIE = IRPT_USER_ENABLE_CLC3PIE ;
	IEC7bits.CLC3NIE = IRPT_USER_ENABLE_CLC3NIE ;
	IEC7bits.CLC4PIE = IRPT_USER_ENABLE_CLC4PIE ;
	IEC7bits.CLC4NIE = IRPT_USER_ENABLE_CLC4NIE ;
#endif 

/*-----------------------------------------------------------------------*/
/* IEC8レジスタ */
/*-----------------------------------------------------------------------*/
	IEC8 =  IRPT_USER_ENABLE_IOM1IE  << _IEC8_IOM1IE_POSITION | 
			IRPT_USER_ENABLE_IOM2IE  << _IEC8_IOM2IE_POSITION | 
			IRPT_USER_ENABLE_IOM3IE  << _IEC8_IOM3IE_POSITION | 
			IRPT_USER_ENABLE_IOM4IE  << _IEC8_IOM4IE_POSITION ;
#ifdef DEF_BITNAME
	IEC8bits.IOM1IE = IRPT_USER_ENABLE_IOM1IE ;
	IEC8bits.IOM2IE = IRPT_USER_ENABLE_IOM2IE ;
	IEC8bits.IOM3IE = IRPT_USER_ENABLE_IOM3IE ;
	IEC8bits.IOM4IE = IRPT_USER_ENABLE_IOM4IE ;
#endif 
} 
/*----------------------------------------------------------------------------*/
/*
* @fn           vdg_Interrupt_Set_IPC_Register(void) 
* @brief           割り込み優先度レジスタを初期設定します 
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_Interrupt_Set_IPC_Register(void)
{
   /*-----------------------------------------------------------------------*/
	/* IPC0レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC0 =	IRPT_USER_PRIORITY_IVTCIP << 0U | 
			IRPT_USER_PRIORITY_CPUFPUIP << 4U | 
			IRPT_USER_PRIORITY_XRAMECCIP << 8U | 
			IRPT_USER_PRIORITY_YRAMECCIP << 12U | 
			IRPT_USER_PRIORITY_PBERRIP << 16U | 
			IRPT_USER_PRIORITY_NVMECCIP << 20U | 
			IRPT_USER_PRIORITY_NVMIP << 24U | 
			IRPT_USER_PRIORITY_NVMIP << 28U ;

	
	#ifdef DEF_BITNAME
		IPC0bits.IVTCIP = IRPT_USER_PRIORITY_IVTCIP;
		IPC0bits.CPUFPUIP = IRPT_USER_PRIORITY_CPUFPUIP;
		IPC0bits.XRAMECCIP = IRPT_USER_PRIORITY_XRAMECCIP;
		IPC0bits.YRAMECCIP = IRPT_USER_PRIORITY_YRAMECCIP;
		IPC0bits.PBERRIP = IRPT_USER_PRIORITY_PBERRIP;
		IPC0bits.NVMECCIP = IRPT_USER_PRIORITY_NVMECCIP;
		IPC0bits.NVMIP = IRPT_USER_PRIORITY_NVMIP;
		IPC0bits.NVMCRCIP = IRPT_USER_PRIORITY_NVMIP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC1レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC1 =	IRPT_USER_PRIORITY_CLKFAILIP << 4U | 
			IRPT_USER_PRIORITY_CLKERRIP << 8U | 
			IRPT_USER_PRIORITY_C1FAILIP << 12U | 
			IRPT_USER_PRIORITY_C1WARNIP << 16U | 
			IRPT_USER_PRIORITY_C1MONIP << 20U | 
			IRPT_USER_PRIORITY_C1RDYIP << 24U | 
			IRPT_USER_PRIORITY_C2FAILIP << 28U ;
	#ifdef DEF_BITNAME
		IPC1bits.CLKFAILIP = IRPT_USER_PRIORITY_CLKFAILIP;
		IPC1bits.CLKERRIP = IRPT_USER_PRIORITY_CLKERRIP;
		IPC1bits.C1FAILIP = IRPT_USER_PRIORITY_C1FAILIP;
		IPC1bits.C1WARNIP = IRPT_USER_PRIORITY_C1WARNIP;
		IPC1bits.C1MONIP = IRPT_USER_PRIORITY_C1MONIP;
		IPC1bits.C1RDYIP = IRPT_USER_PRIORITY_C1RDYIP;
		IPC1bits.C2FAILIP = IRPT_USER_PRIORITY_C2FAILIP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC2レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC2 =   IRPT_USER_PRIORITY_C2WARNIP << 0U | 
			IRPT_USER_PRIORITY_C2MONIP << 4U | 
			IRPT_USER_PRIORITY_C2RDYIP << 8U | 
			IRPT_USER_PRIORITY_C3FAILIP << 12U | 
			IRPT_USER_PRIORITY_C3WARNIP << 6U | 
			IRPT_USER_PRIORITY_C3MONIP << 20U | 
			IRPT_USER_PRIORITY_C3RDYIP << 24U | 
			IRPT_USER_PRIORITY_C4FAILIP << 28U ; 

	#ifdef DEF_BITNAME
		IPC2bits.C2WARNIP = IRPT_USER_PRIORITY_C2WARNIP;
		IPC2bits.C2MONIP = IRPT_USER_PRIORITY_C2MONIP;
		IPC2bits.C2RDYIP = IRPT_USER_PRIORITY_C2RDYIP;
		IPC2bits.C3FAILIP = IRPT_USER_PRIORITY_C3FAILIP;
		IPC2bits.C3WARNIP = IRPT_USER_PRIORITY_C3WARNIP;
		IPC2bits.C3MONIP = IRPT_USER_PRIORITY_C3MONIP;
		IPC2bits.C3RDYIP = IRPT_USER_PRIORITY_C3RDYIP;
		IPC2bits.C4FAILIP = IRPT_USER_PRIORITY_C4FAILIP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC3レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC3 =  IRPT_USER_PRIORITY_C4WARNIP << 0U | 
			IRPT_USER_PRIORITY_C4MONIP << 4U | 
			IRPT_USER_PRIORITY_C4RDYIP << 8U | 
			IRPT_USER_PRIORITY_WDTIP << 16U ;
	#ifdef DEF_BITNAME
		IPC3bits.C4WARNIP = IRPT_USER_PRIORITY_C4WARNIP;
		IPC3bits.C4MONIP = IRPT_USER_PRIORITY_C4MONIP;
		IPC3bits.C4RDYIP = IRPT_USER_PRIORITY_C4RDYIP;
		IPC3bits.WDTIP = IRPT_USER_PRIORITY_WDTIP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC4レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC4 =  IRPT_USER_PRIORITY_INT0IP << 4U | 
			IRPT_USER_PRIORITY_INT1IP << 8U | 
			IRPT_USER_PRIORITY_INT2IP << 12U | 
			IRPT_USER_PRIORITY_INT3IP << 16U | 
			IRPT_USER_PRIORITY_INT4IP << 20U | 
			IRPT_USER_PRIORITY_PEVTAIP << 24U | 
			IRPT_USER_PRIORITY_PEVTBIP << 28U ;
	#ifdef DEF_BITNAME
		IPC4bits.INT0IP = IRPT_USER_PRIORITY_INT0IP;
		IPC4bits.INT1IP = IRPT_USER_PRIORITY_INT1IP;
		IPC4bits.INT2IP = IRPT_USER_PRIORITY_INT2IP;
		IPC4bits.INT3IP = IRPT_USER_PRIORITY_INT3IP;
		IPC4bits.INT4IP = IRPT_USER_PRIORITY_INT4IP;
		IPC4bits.PEVTAIP = IRPT_USER_PRIORITY_PEVTAIP;
		IPC4bits.PEVTBIP = IRPT_USER_PRIORITY_PEVTBIP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC5レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC5 =  IRPT_USER_PRIORITY_PEVTCIP << 0U | 
			IRPT_USER_PRIORITY_PEVTDIP << 4U | 
			IRPT_USER_PRIORITY_PEVTEIP << 8U | 
			IRPT_USER_PRIORITY_PEVTFIP << 12U | 
			IRPT_USER_PRIORITY_PWM1IP << 16U | 
			IRPT_USER_PRIORITY_PWM2IP << 20U | 
			IRPT_USER_PRIORITY_PWM3IP << 24U | 
			IRPT_USER_PRIORITY_PWM4IP << 28U ;
	#ifdef DEF_BITNAME
		IPC5bits.PEVTCIP = IRPT_USER_PRIORITY_PEVTCIP;
		IPC5bits.PEVTDIP = IRPT_USER_PRIORITY_PEVTDIP;
		IPC5bits.PEVTEIP = IRPT_USER_PRIORITY_PEVTEIP;
		IPC5bits.PEVTFIP = IRPT_USER_PRIORITY_PEVTFIP;
		IPC5bits.PWM1IP = IRPT_USER_PRIORITY_PWM1IP;
		IPC5bits.PWM2IP = IRPT_USER_PRIORITY_PWM2IP;
		IPC5bits.PWM3IP = IRPT_USER_PRIORITY_PWM3IP;
		IPC5bits.PWM4IP = IRPT_USER_PRIORITY_PWM4IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC6レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC6 =  IRPT_USER_PRIORITY_T1IP << 0U | 
			IRPT_USER_PRIORITY_CCT1IP << 4U | 
			IRPT_USER_PRIORITY_CCP1IP << 8U | 
			IRPT_USER_PRIORITY_CCT2IP << 12U | 
			IRPT_USER_PRIORITY_CCP2IP << 16U | 
			IRPT_USER_PRIORITY_CCT3IP << 20U | 
			IRPT_USER_PRIORITY_CCP3IP << 24U | 
			IRPT_USER_PRIORITY_CCT4IP << 28U ;
	#ifdef DEF_BITNAME
		IPC6bits.T1IP = IRPT_USER_PRIORITY_T1IP;
		IPC6bits.CCT1IP = IRPT_USER_PRIORITY_CCT1IP;
		IPC6bits.CCP1IP = IRPT_USER_PRIORITY_CCP1IP;
		IPC6bits.CCT2IP = IRPT_USER_PRIORITY_CCT2IP;
		IPC6bits.CCP2IP = IRPT_USER_PRIORITY_CCP2IP;
		IPC6bits.CCT3IP = IRPT_USER_PRIORITY_CCT3IP;
		IPC6bits.CCP3IP = IRPT_USER_PRIORITY_CCP3IP;
		IPC6bits.CCT4IP = IRPT_USER_PRIORITY_CCT4IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC7レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC7 =  IRPT_USER_PRIORITY_CCP4IP << 0U | 
			IRPT_USER_PRIORITY_SPI1RXIP << 28U ;
	#ifdef DEF_BITNAME
		IPC7bits.CCP4IP = IRPT_USER_PRIORITY_CCP4IP;
		IPC7bits.SPI1RXIP = IRPT_USER_PRIORITY_SPI1RXIP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC8レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC8 =  IRPT_USER_PRIORITY_SPI1TXIP << 0U | 
			IRPT_USER_PRIORITY_SPI1EIP << 4U | 
			IRPT_USER_PRIORITY_SPI2RXIP << 8U | 
			IRPT_USER_PRIORITY_SPI2TXIP << 12U | 
			IRPT_USER_PRIORITY_SPI2EIP << 16U | 
			IRPT_USER_PRIORITY_SPI3RXIP << 20U | 
			IRPT_USER_PRIORITY_SPI3TXIP << 24U | 
			IRPT_USER_PRIORITY_SPI3EIP << 28U ;
	#ifdef DEF_BITNAME
		IPC8bits.SPI1TXIP = IRPT_USER_PRIORITY_SPI1TXIP;
		IPC8bits.SPI1EIP = IRPT_USER_PRIORITY_SPI1EIP;
		IPC8bits.SPI2RXIP = IRPT_USER_PRIORITY_SPI2RXIP;
		IPC8bits.SPI2TXIP = IRPT_USER_PRIORITY_SPI2TXIP;
		IPC8bits.SPI2EIP = IRPT_USER_PRIORITY_SPI2EIP;
		IPC8bits.SPI3RXIP = IRPT_USER_PRIORITY_SPI3RXIP;
		IPC8bits.SPI3TXIP = IRPT_USER_PRIORITY_SPI3TXIP;
		IPC8bits.SPI3EIP = IRPT_USER_PRIORITY_SPI3EIP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC9レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC9 =  IRPT_USER_PRIORITY_DMA0IP << 0U | 
			IRPT_USER_PRIORITY_DMA1IP << 4U | 
			IRPT_USER_PRIORITY_DMA2IP << 8U | 
			IRPT_USER_PRIORITY_DMA3IP << 12U | 
			IRPT_USER_PRIORITY_CMP1IP << 16U | 
			IRPT_USER_PRIORITY_CMP2IP << 18U | 
			IRPT_USER_PRIORITY_CMP3IP << 20U ;
	#ifdef DEF_BITNAME
		IPC9bits.DMA0IP = IRPT_USER_PRIORITY_DMA0IP;
		IPC9bits.DMA1IP = IRPT_USER_PRIORITY_DMA1IP;
		IPC9bits.DMA2IP = IRPT_USER_PRIORITY_DMA2IP;
		IPC9bits.DMA3IP = IRPT_USER_PRIORITY_DMA3IP;
		IPC9bits.CMP1IP = IRPT_USER_PRIORITY_CMP1IP;
		IPC9bits.CMP2IP = IRPT_USER_PRIORITY_CMP2IP;
		IPC9bits.CMP3IP = IRPT_USER_PRIORITY_CMP3IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC10レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC10 = IRPT_USER_PRIORITY_I2C1EIP << 0U | 
			IRPT_USER_PRIORITY_I2C1IP << 4U | 
			IRPT_USER_PRIORITY_I2C1RXIP << 8U | 
			IRPT_USER_PRIORITY_I2C1TXIP << 12U | 
			IRPT_USER_PRIORITY_I2C2EIP << 16U | 
			IRPT_USER_PRIORITY_I2C2IP << 20U | 
			IRPT_USER_PRIORITY_I2C2RXIP << 24U | 
			IRPT_USER_PRIORITY_I2C2TXIP << 28U ;
	#ifdef DEF_BITNAME
		IPC10bits.I2C1EIP = IRPT_USER_PRIORITY_I2C1EIP;
		IPC10bits.I2C1IP = IRPT_USER_PRIORITY_I2C1IP;
		IPC10bits.I2C1RXIP = IRPT_USER_PRIORITY_I2C1RXIP;
		IPC10bits.I2C1TXIP = IRPT_USER_PRIORITY_I2C1TXIP;
		IPC10bits.I2C2EIP = IRPT_USER_PRIORITY_I2C2EIP;
		IPC10bits.I2C2IP = IRPT_USER_PRIORITY_I2C2IP;
		IPC10bits.I2C2RXIP = IRPT_USER_PRIORITY_I2C2RXIP;
		IPC10bits.I2C2TXIP = IRPT_USER_PRIORITY_I2C2TXIP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC11レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC11 = IRPT_USER_PRIORITY_U1RXIP << 4U | 
			IRPT_USER_PRIORITY_U1TXIP << 8U | 
			IRPT_USER_PRIORITY_U1EIP << 12U | 
			IRPT_USER_PRIORITY_U1EVTIP << 16U | 
			IRPT_USER_PRIORITY_U2RXIP << 20U | 
			IRPT_USER_PRIORITY_U2TXIP << 24U | 
			IRPT_USER_PRIORITY_U2EIP << 28U ;
	#ifdef DEF_BITNAME
		IPC11bits.U1RXIP = IRPT_USER_PRIORITY_U1RXIP;
		IPC11bits.U1TXIP = IRPT_USER_PRIORITY_U1TXIP;
		IPC11bits.U1EIP = IRPT_USER_PRIORITY_U1EIP;
		IPC11bits.U1EVTIP = IRPT_USER_PRIORITY_U1EVTIP;
		IPC11bits.U2RXIP = IRPT_USER_PRIORITY_U2RXIP;
		IPC11bits.U2TXIP = IRPT_USER_PRIORITY_U2TXIP;
		IPC11bits.U2EIP = IRPT_USER_PRIORITY_U2EIP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC12レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC12 = IRPT_USER_PRIORITY_U2EVTIP << 0U | 
			IRPT_USER_PRIORITY_U3RXIP << 4U | 
			IRPT_USER_PRIORITY_U3TXIP << 8U | 
			IRPT_USER_PRIORITY_U3EIP << 12U | 
			IRPT_USER_PRIORITY_U3EVTIP << 16U ; 

	#ifdef DEF_BITNAME
		IPC12bits.U2EVTIP = IRPT_USER_PRIORITY_U2EVTIP;
		IPC12bits.U3RXIP = IRPT_USER_PRIORITY_U3RXIP;
		IPC12bits.U3TXIP = IRPT_USER_PRIORITY_U3TXIP;
		IPC12bits.U3EIP = IRPT_USER_PRIORITY_U3EIP;
		IPC12bits.U3EVTIP = IRPT_USER_PRIORITY_U3EVTIP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC13レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC13 = IRPT_USER_PRIORITY_SENT1IP << 4U | 
			IRPT_USER_PRIORITY_SENT1EIP << 8U | 
			IRPT_USER_PRIORITY_SENT2IP << 12U | 
			IRPT_USER_PRIORITY_SENT2EIP << 16U | 
			IRPT_USER_PRIORITY_DMA4IP << 20U | 
			IRPT_USER_PRIORITY_DMA5IP << 24U ;
	#ifdef DEF_BITNAME
		IPC13bits.SENT1IP = IRPT_USER_PRIORITY_SENT1IP;
		IPC13bits.SENT1EIP = IRPT_USER_PRIORITY_SENT1EIP;
		IPC13bits.SENT2IP = IRPT_USER_PRIORITY_SENT2IP;
		IPC13bits.SENT2EIP = IRPT_USER_PRIORITY_SENT2EIP;
		IPC13bits.DMA4IP = IRPT_USER_PRIORITY_DMA4IP;
		IPC13bits.DMA5IP = IRPT_USER_PRIORITY_DMA5IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC14レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC14 = IRPT_USER_PRIORITY_CNAIP << 4U | 
			IRPT_USER_PRIORITY_CNBIP << 8U | 
			IRPT_USER_PRIORITY_CNCIP << 12U | 
			IRPT_USER_PRIORITY_CNDIP << 20U ;
	#ifdef DEF_BITNAME
		IPC14bits.CNAIP = IRPT_USER_PRIORITY_CNAIP;
		IPC14bits.CNBIP = IRPT_USER_PRIORITY_CNBIP;
		IPC14bits.CNCIP = IRPT_USER_PRIORITY_CNCIP;
		IPC14bits.CNDIP = IRPT_USER_PRIORITY_CNDIP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC15レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC15 = IRPT_USER_PRIORITY_QEI1IP << 20U ;
	#ifdef DEF_BITNAME
		IPC15bits.QEI1IP = IRPT_USER_PRIORITY_QEI1IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC16レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC16 = IRPT_USER_PRIORITY_BISS1IP << 4U | 
			IRPT_USER_PRIORITY_BISSE1IP << 8U | 
			IRPT_USER_PRIORITY_CRCIP << 12U | 
			IRPT_USER_PRIORITY_ICDIP << 16U | 
			IRPT_USER_PRIORITY_PTGSTPIP << 24U | 
			IRPT_USER_PRIORITY_PTGWDTIP << 28U ;
	#ifdef DEF_BITNAME
		IPC16bits.BISS1IP = IRPT_USER_PRIORITY_BISS1IP;
		IPC16bits.BISSE1IP = IRPT_USER_PRIORITY_BISSE1IP;
		IPC16bits.CRCIP = IRPT_USER_PRIORITY_CRCIP;
		IPC16bits.ICDIP = IRPT_USER_PRIORITY_ICDIP;
		IPC16bits.PTGSTEPIP = IRPT_USER_PRIORITY_PTGSTPIP;
		IPC16bits.PTGWDTIP = IRPT_USER_PRIORITY_PTGWDTIP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC17レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC17 = IRPT_USER_PRIORITY_PTG0IP << 0U | 
			IRPT_USER_PRIORITY_PTG1IP << 4U | 
			IRPT_USER_PRIORITY_PTG2IP << 8U | 
			IRPT_USER_PRIORITY_PTG3IP << 12U ;
	#ifdef DEF_BITNAME
		IPC17bits.PTG0IP = IRPT_USER_PRIORITY_PTG0IP;
		IPC17bits.PTG1IP = IRPT_USER_PRIORITY_PTG1IP;
		IPC17bits.PTG2IP = IRPT_USER_PRIORITY_PTG2IP;
		IPC17bits.PTG3IP = IRPT_USER_PRIORITY_PTG3IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC18レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC18 = IRPT_USER_PRIORITY_AD1CH0IP << 8U | 
			IRPT_USER_PRIORITY_AD1CMP0IP << 12U | 
			IRPT_USER_PRIORITY_AD1CH1IP << 16U | 
			IRPT_USER_PRIORITY_AD1CMP1IP << 20U | 
			IRPT_USER_PRIORITY_AD1CH2IP << 24U | 
			IRPT_USER_PRIORITY_AD1CMP2IP << 8U ;
	#ifdef DEF_BITNAME
		IPC18bits.AD1CH0IP = IRPT_USER_PRIORITY_AD1CH0IP;
		IPC18bits.AD1CMP0IP = IRPT_USER_PRIORITY_AD1CMP0IP;
		IPC18bits.AD1CH1IP = IRPT_USER_PRIORITY_AD1CH1IP;
		IPC18bits.AD1CMP1IP = IRPT_USER_PRIORITY_AD1CMP1IP;
		IPC18bits.AD1CH2IP = IRPT_USER_PRIORITY_AD1CH2IP;
		IPC18bits.AD1CMP2IP = IRPT_USER_PRIORITY_AD1CMP2IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC19レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC19 = IRPT_USER_PRIORITY_AD1CH3IP << 0U | 
			IRPT_USER_PRIORITY_AD1CMP3IP << 4U | 
			IRPT_USER_PRIORITY_AD1CH4IP << 8U | 
			IRPT_USER_PRIORITY_AD1CMP4IP << 12U | 
			IRPT_USER_PRIORITY_AD1CH5IP << 16U | 
			IRPT_USER_PRIORITY_AD1CMP5IP << 20U | 
			IRPT_USER_PRIORITY_AD1CH6IP << 24U | 
			IRPT_USER_PRIORITY_AD1CMP6IP << 28U ;
	#ifdef DEF_BITNAME
		IPC19bits.AD1CH3IP = IRPT_USER_PRIORITY_AD1CH3IP;
		IPC19bits.AD1CMP3IP = IRPT_USER_PRIORITY_AD1CMP3IP;
		IPC19bits.AD1CH4IP = IRPT_USER_PRIORITY_AD1CH4IP;
		IPC19bits.AD1CMP4IP = IRPT_USER_PRIORITY_AD1CMP4IP;
		IPC19bits.AD1CH5IP = IRPT_USER_PRIORITY_AD1CH5IP;
		IPC19bits.AD1CMP5IP = IRPT_USER_PRIORITY_AD1CMP5IP;
		IPC19bits.AD1CH6IP = IRPT_USER_PRIORITY_AD1CH6IP;
		IPC19bits.AD1CMP6IP = IRPT_USER_PRIORITY_AD1CMP6IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC20レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC20 = IRPT_USER_PRIORITY_AD1CH7IP << 0U | 
			IRPT_USER_PRIORITY_AD1CMP7IP << 4U | 
			IRPT_USER_PRIORITY_AD1CH8IP << 8U | 
			IRPT_USER_PRIORITY_AD1CMP8IP << 12U | 
			IRPT_USER_PRIORITY_AD1CH9IP << 16U | 
			IRPT_USER_PRIORITY_AD1CMP9IP << 20U | 
			IRPT_USER_PRIORITY_AD1CH10IP << 24U | 
			IRPT_USER_PRIORITY_AD1CMP10IP << 28U ;
	#ifdef DEF_BITNAME
		IPC20bits.AD1CH7IP = IRPT_USER_PRIORITY_AD1CH7IP;
		IPC20bits.AD1CMP7IP = IRPT_USER_PRIORITY_AD1CMP7IP;
		IPC20bits.AD1CH8IP = IRPT_USER_PRIORITY_AD1CH8IP;
		IPC20bits.AD1CMP8IP = IRPT_USER_PRIORITY_AD1CMP8IP;
		IPC20bits.AD1CH9IP = IRPT_USER_PRIORITY_AD1CH9IP;
		IPC20bits.AD1CMP9IP = IRPT_USER_PRIORITY_AD1CMP9IP;
		IPC20bits.AD1CH10IP = IRPT_USER_PRIORITY_AD1CH10IP;
		IPC20bits.AD1CMP10IP = IRPT_USER_PRIORITY_AD1CMP10IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC21レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC21 = IRPT_USER_PRIORITY_AD1CH11IP << 0U | 
			IRPT_USER_PRIORITY_AD1CMP11IP << 4U | 
			IRPT_USER_PRIORITY_AD1CH12IP << 8U | 
			IRPT_USER_PRIORITY_AD1CMP12IP << 12U | 
			IRPT_USER_PRIORITY_AD1CH13IP << 16U | 
			IRPT_USER_PRIORITY_AD1CMP13IP << 20U | 
			IRPT_USER_PRIORITY_AD1CH14IP << 24U | 
			IRPT_USER_PRIORITY_AD1CMP14IP << 28U ;
	#ifdef DEF_BITNAME
		IPC21bits.AD1CH11IP = IRPT_USER_PRIORITY_AD1CH11IP;
		IPC21bits.AD1CMP11IP = IRPT_USER_PRIORITY_AD1CMP11IP;
		IPC21bits.AD1CH12IP = IRPT_USER_PRIORITY_AD1CH12IP;
		IPC21bits.AD1CMP12IP = IRPT_USER_PRIORITY_AD1CMP12IP;
		IPC21bits.AD1CH13IP = IRPT_USER_PRIORITY_AD1CH13IP;
		IPC21bits.AD1CMP13IP = IRPT_USER_PRIORITY_AD1CMP13IP;
		IPC21bits.AD1CH14IP = IRPT_USER_PRIORITY_AD1CH14IP;
		IPC21bits.AD1CMP14IP = IRPT_USER_PRIORITY_AD1CMP14IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC22レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC22 = IRPT_USER_PRIORITY_AD1CH15IP << 0U | 
			IRPT_USER_PRIORITY_AD1CMP15IP << 4U | 
			IRPT_USER_PRIORITY_AD1CH16IP << 8U | 
			IRPT_USER_PRIORITY_AD1CMP16IP << 12U | 
			IRPT_USER_PRIORITY_AD1CH17IP << 16U | 
			IRPT_USER_PRIORITY_AD1CMP17IP << 20U | 
			IRPT_USER_PRIORITY_AD1CH18IP << 24U | 
			IRPT_USER_PRIORITY_AD1CMP18IP << 28U ;
	#ifdef DEF_BITNAME
		IPC22bits.AD1CH15IP = IRPT_USER_PRIORITY_AD1CH15IP;
		IPC22bits.AD1CMP15IP = IRPT_USER_PRIORITY_AD1CMP15IP;
		IPC22bits.AD1CH16IP = IRPT_USER_PRIORITY_AD1CH16IP;
		IPC22bits.AD1CMP16IP = IRPT_USER_PRIORITY_AD1CMP16IP;
		IPC22bits.AD1CH17IP = IRPT_USER_PRIORITY_AD1CH17IP;
		IPC22bits.AD1CMP17IP = IRPT_USER_PRIORITY_AD1CMP17IP;
		IPC22bits.AD1CH18IP = IRPT_USER_PRIORITY_AD1CH18IP;
		IPC22bits.AD1CMP18IP = IRPT_USER_PRIORITY_AD1CMP18IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC23レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC23 = IRPT_USER_PRIORITY_AD1CH19IP << 0U | 
			IRPT_USER_PRIORITY_AD1CMP19IP << 4U | 
			IRPT_USER_PRIORITY_AD2CH0IP << 16U | 
			IRPT_USER_PRIORITY_AD2CMP0IP << 20U | 
			IRPT_USER_PRIORITY_AD2CH1IP << 24U | 
			IRPT_USER_PRIORITY_AD2CMP1IP << 28U ;
	#ifdef DEF_BITNAME
		IPC23bits.AD1CH19IP = IRPT_USER_PRIORITY_AD1CH19IP;
		IPC23bits.AD1CMP19IP = IRPT_USER_PRIORITY_AD1CMP19IP;
		IPC23bits.AD2CH0IP = IRPT_USER_PRIORITY_AD2CH0IP;
		IPC23bits.AD2CMP0IP = IRPT_USER_PRIORITY_AD2CMP0IP;
		IPC23bits.AD2CH1IP = IRPT_USER_PRIORITY_AD2CH1IP
		IPC23bits.AD2CMP1IP = IRPT_USER_PRIORITY_AD2CMP1IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC24レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC24 = IRPT_USER_PRIORITY_AD2CH2IP << 0U | 
			IRPT_USER_PRIORITY_AD2CMP2IP << 0U | 
			IRPT_USER_PRIORITY_AD2CH3IP << 0U | 
			IRPT_USER_PRIORITY_AD2CMP3IP << 0U | 
			IRPT_USER_PRIORITY_AD2CH4IP << 0U | 
			IRPT_USER_PRIORITY_AD2CMP4IP << 0U | 
			IRPT_USER_PRIORITY_AD2CH5IP << 0U | 
			IRPT_USER_PRIORITY_AD2CMP5IP << 0U ;
	#ifdef DEF_BITNAME
		IPC24bits.AD2CH2IP = IRPT_USER_PRIORITY_AD2CH2IP;
		IPC24bits.AD2CMP2IP = IRPT_USER_PRIORITY_AD2CMP2IP;
		IPC24bits.AD2CH3IP = IRPT_USER_PRIORITY_AD2CH3IP;
		IPC24bits.AD2CMP3IP = IRPT_USER_PRIORITY_AD2CMP3IP;
		IPC24bits.AD2CH4IP = IRPT_USER_PRIORITY_AD2CH4IP;
		IPC24bits.AD2CMP4IP = IRPT_USER_PRIORITY_AD2CMP4IP;
		IPC24bits.AD2CH5IP = IRPT_USER_PRIORITY_AD2CH5IP;
		IPC24bits.AD2CMP5IP = IRPT_USER_PRIORITY_AD2CMP5IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC25レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC25 = IRPT_USER_PRIORITY_AD2CH6IP << 0U | 
			IRPT_USER_PRIORITY_AD2CMP6IP << 4U | 
			IRPT_USER_PRIORITY_AD2CH7IP << 8U | 
			IRPT_USER_PRIORITY_AD2CMP7IP << 12U | 
			IRPT_USER_PRIORITY_AD2CH8IP << 16U | 
			IRPT_USER_PRIORITY_AD2CMP8IP << 20U | 
			IRPT_USER_PRIORITY_AD2CH9IP << 24U | 
			IRPT_USER_PRIORITY_AD2CMP9IP << 28U ;
	#ifdef DEF_BITNAME
		IPC25bits.AD2CH6IP = IRPT_USER_PRIORITY_AD2CH6IP;
		IPC25bits.AD2CMP6IP = IRPT_USER_PRIORITY_AD2CMP6IP;
		IPC25bits.AD2CH7IP = IRPT_USER_PRIORITY_AD2CH7IP;
		IPC25bits.AD2CMP7IP = IRPT_USER_PRIORITY_AD2CMP7IP;
		IPC25bits.AD2CH8IP = IRPT_USER_PRIORITY_AD2CH8IP;
		IPC25bits.AD2CMP8IP = IRPT_USER_PRIORITY_AD2CMP8IP;
		IPC25bits.AD2CH9IP = IRPT_USER_PRIORITY_AD2CH9IP;
		IPC25bits.AD2CMP9IP = IRPT_USER_PRIORITY_AD2CMP9IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC26レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC26 = IRPT_USER_PRIORITY_AD2CH10IP << 0U | 
			IRPT_USER_PRIORITY_AD2CMP10IP << 4U | 
			IRPT_USER_PRIORITY_AD2CH11IP << 8U | 
			IRPT_USER_PRIORITY_AD2CMP11IP << 12U | 
			IRPT_USER_PRIORITY_AD2CH12IP << 16U | 
			IRPT_USER_PRIORITY_AD2CMP12IP << 20U | 
			IRPT_USER_PRIORITY_AD2CH13IP << 24U | 
			IRPT_USER_PRIORITY_AD2CMP13IP << 28U ;
	#ifdef DEF_BITNAME
		IPC26bits.AD2CH10IP = IRPT_USER_PRIORITY_AD2CH10IP;
		IPC26bits.AD2CMP10IP = IRPT_USER_PRIORITY_AD2CMP10IP;
		IPC26bits.AD2CH11IP = IRPT_USER_PRIORITY_AD2CH11IP;
		IPC26bits.AD2CMP11IP = IRPT_USER_PRIORITY_AD2CMP11IP;
		IPC26bits.AD2CH12IP = IRPT_USER_PRIORITY_AD2CH12IP;
		IPC26bits.AD2CMP12IP = IRPT_USER_PRIORITY_AD2CMP12IP;
		IPC26bits.AD2CH13IP = IRPT_USER_PRIORITY_AD2CH13IP;
		IPC26bits.AD2CMP13IP = IRPT_USER_PRIORITY_AD2CMP13IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC27レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC27 = IRPT_USER_PRIORITY_AD2CH14IP << 0U | 
			IRPT_USER_PRIORITY_AD2CMP14IP << 4U | 
			IRPT_USER_PRIORITY_AD2CH15IP << 8U | 
			IRPT_USER_PRIORITY_AD2CMP15IP << 12U | 
			IRPT_USER_PRIORITY_AD2CH16IP << 16U | 
			IRPT_USER_PRIORITY_AD2CMP16IP << 20U | 
			IRPT_USER_PRIORITY_AD2CH17IP << 24U | 
			IRPT_USER_PRIORITY_AD2CMP17IP << 28U ;
	#ifdef DEF_BITNAME
		IPC27bits.AD2CH14IP = IRPT_USER_PRIORITY_AD2CH14IP;
		IPC27bits.AD2CMP14IP = IRPT_USER_PRIORITY_AD2CMP14IP;
		IPC27bits.AD2CH15IP = IRPT_USER_PRIORITY_AD2CH15IP;
		IPC27bits.AD2CMP15IP = IRPT_USER_PRIORITY_AD2CMP15IP;
		IPC27bits.AD2CH16IP = IRPT_USER_PRIORITY_AD2CH16IP;
		IPC27bits.AD2CMP16IP = IRPT_USER_PRIORITY_AD2CMP16IP;
		IPC27bits.AD2CH17IP = IRPT_USER_PRIORITY_AD2CH17IP;
		IPC27bits.AD2CMP17IP = IRPT_USER_PRIORITY_AD2CMP17IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC28レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC28 = IRPT_USER_PRIORITY_AD2CH18IP << 0U | 
			IRPT_USER_PRIORITY_AD2CMP18IP << 4U | 
			IRPT_USER_PRIORITY_AD2CH19IP << 8U | 
			IRPT_USER_PRIORITY_AD2CMP19IP << 12U ;
	#ifdef DEF_BITNAME
		IPC28bits.AD2CH18IP = IRPT_USER_PRIORITY_AD2CH18IP;
		IPC28bits.AD2CMP18IP = IRPT_USER_PRIORITY_AD2CMP18IP;
		IPC28bits.AD2CH19IP = IRPT_USER_PRIORITY_AD2CH19IP;
		IPC28bits.AD2CMP19IP = IRPT_USER_PRIORITY_AD2CMP19IP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC29レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC29 = IRPT_USER_PRIORITY_CLC1PIP << 0U | 
			IRPT_USER_PRIORITY_CLC1NIP << 4U | 
			IRPT_USER_PRIORITY_CLC2PIP << 8U | 
			IRPT_USER_PRIORITY_CLC2NIP << 12U | 
			IRPT_USER_PRIORITY_CLC3PIP << 16U | 
			IRPT_USER_PRIORITY_CLC3NIP << 20U | 
			IRPT_USER_PRIORITY_CLC4PIP << 24U | 
			IRPT_USER_PRIORITY_CLC4NIP << 28U ;
	#ifdef DEF_BITNAME
		IPC29bits.CLC1PIP = IRPT_USER_PRIORITY_CLC1PIP;
		IPC29bits.CLC1NIP = IRPT_USER_PRIORITY_CLC1NIP;
		IPC29bits.CLC2PIP = IRPT_USER_PRIORITY_CLC2PIP;
		IPC29bits.CLC2NIP = IRPT_USER_PRIORITY_CLC2NIP;
		IPC29bits.CLC3PIP = IRPT_USER_PRIORITY_CLC3PIP;
		IPC29bits.CLC3NIP = IRPT_USER_PRIORITY_CLC3NIP;
		IPC29bits.CLC4PIP = IRPT_USER_PRIORITY_CLC4PIP;
		IPC29bits.CLC4NIP = IRPT_USER_PRIORITY_CLC4NIP;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IPC35レジスタ */
	/*-----------------------------------------------------------------------*/
	IPC35 = IRPT_USER_PRIORITY_IOM1IP << 12U | 
			IRPT_USER_PRIORITY_IOM2IP << 16U | 
			IRPT_USER_PRIORITY_IOM3IP << 20U | 
			IRPT_USER_PRIORITY_IOM4IP << 24U ;
	#ifdef DEF_BITNAME
		IPC35bits.IOM1IP = IRPT_USER_PRIORITY_IOM1IP;
		IPC35bits.IOM2IP = IRPT_USER_PRIORITY_IOM2IP;
		IPC35bits.IOM3IP = IRPT_USER_PRIORITY_IOM3IP;
		IPC35bits.IOM4IP = IRPT_USER_PRIORITY_IOM4IP;
	#endif 
}

/*----------------------------------------------------------------------------*/
/*
* @fn           vdg_Interrupt_Set_CON_Register(void)
* @brief           割り込みレジスタを初期設定します
* @detail 
 */
/*----------------------------------------------------------------------------*/
void vdg_Interrupt_Set_CON_Register(void)
{
	/*-----------------------------------------------------------------------*/
	/* INTCON1レジスタ */
	/*-----------------------------------------------------------------------*/
	INTCON1 = 0x00000000u;
	#ifdef DEF_BITNAME
		INTCON1bits.BADOPERR = 0u;
		INTCON1bits.ADDRERR = 0u;
		INTCON1bits.STKERR = 0u;
		INTCON1bits.GIE = 0u;
		INTCON1bits.NSTDIS = 0u;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* INTCON2レジスタ */
	/*-----------------------------------------------------------------------*/
	INTCON2 = 0x00000000u;
	#ifdef DEF_BITNAME
		INTCON2bits.INT0EP = 0u;
		INTCON2bits.INT1EP = 0u;
		INTCON2bits.INT2EP = 0u;
		INTCON2bits.INT3EP = 0u;
		INTCON2bits.INT4EP = 0u;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* INTCON3レジスタ */
	/*-----------------------------------------------------------------------*/
	INTCON3 = 0x00000000u;
	#ifdef DEF_BITNAME
		INTCON3bits.BET0 = 0u;
		INTCON3bits.BET1 = 0u;
		INTCON3bits.BET2 = 0u;
		INTCON3bits.BET3 = 0u;
		INTCON3bits.BET4 = 0u;
		INTCON3bits.XRAMBET = 0u;
		INTCON3bits.YRAMBET = 0u;
		INTCON3bits.DMABET = 0u;
		INTCON3bits.CPUBET = 0u;
		INTCON3bits.ICDBET = 0u;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* INTCON4レジスタ */
	/*-----------------------------------------------------------------------*/
	INTCON4 = 0x00000000u;
	#ifdef DEF_BITNAME
		INTCON4bits.DIV0ERR = 0u;
		INTCON4bits.SFTACERR = 0u;
		INTCON4bits.COVBERR = 0u;
		INTCON4bits.COVAERR = 0u;
		INTCON4bits.OVBERR = 0u;
		INTCON4bits.OVAERR = 0u;
		INTCON4bits.COVTE = 0u;
		INTCON4bits.OVBTE = 0u;
		INTCON4bits.OVATE = 0u;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* INTCON5レジスタ */
	/*-----------------------------------------------------------------------*/
	INTCON5 = 0x00000000u;
	#ifdef DEF_BITNAME
		INTCON5bits.DMT = 0u;
		INTCON5bits.WDT = 0u;
		INTCON5bits.XRAM = 0u;
		INTCON5bits.YRAM = 0u;
		INTCON5bits.SOFT = 0u;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* INTTREGレジスタ */
	/*-----------------------------------------------------------------------*/
	INTTREG = 0x00000000u;
	#ifdef DEF_BITNAME
		INTTREGbits.VECNUM = 0u;
		INTTREGbits.ILR = 0u;
		INTTREGbits.VHOLD = 0u;
	#endif 

	/*-----------------------------------------------------------------------*/
	/* IVTBASEレジスタ */
	/*-----------------------------------------------------------------------*/
	IVTBASE = 0x00000000u;
	/*-----------------------------------------------------------------------*/
	/* IVTCREGレジスタ */
	/*-----------------------------------------------------------------------*/
	IVTCREG = 0x00000000u;
	#ifdef DEF_BITNAME
		IVTCREGbits.IVTC = 0u;
	#endif 

    
} 
/*----------------------------------------------------------------------------*/
/*
* @fn           vdg_Interrupt_Set_Register(void)
* @brief        割り込み関係の全レジスタを初期設定します
* @detail 
*/
/*----------------------------------------------------------------------------*/
void vdg_Interrupt_Set_Register(void)
{
    vdg_Interrupt_Set_IFS_Register();
    vdg_Interrupt_Set_IEC_Register();
    vdg_Interrupt_Set_IPC_Register();
	vdg_Interrupt_Set_CON_Register();
}
