
#ifndef PWM_USER_H
#define	PWM_USER_H

/*----------------------------------------------------------------------------*/
/*インクルードファイル*/
/*----------------------------------------------------------------------------*/
#include "pwm_driver.h"
/*----------------------------------------------------------------------------*/
/*定数定義*/
/*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*/
/* PCLKCON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PCLKCON_LOCK		( PWM_DRV_PCLKCON_LOCK_UNLOCK )
#define PWM_USER_PCLKCON_DIVSEL		( PWM_DRV_PCLKCON_DIVSEL_2X )
#define PWM_USER_PCLKCON_MCLKSEL	( PWM_DRV_PCLKCON_MCLKSEL_STD_SPEED )


#define PWM_USER_FSCL				( 0u )
#define PWM_USER_FSMINPER			( 0u )
#define PWM_USER_FSCL				( 0u )
#define PWM_USER_MPHASE				( 0u )
#define PWM_USER_MDC				( 0u )
#define PWM_USER_MPER				( 0u )
#define PWM_USER_LFSR				( 0u )

/*----------------------------------------------------------------------------*/
/* CMBTRIG */
/*----------------------------------------------------------------------------*/
#define PWM_USER_CMBTRIG_CTA1EN		( PWM_DRV_CMBTRIG_DISABLE )
#define PWM_USER_CMBTRIG_CTA2EN		( PWM_DRV_CMBTRIG_DISABLE )
#define PWM_USER_CMBTRIG_CTA3EN		( PWM_DRV_CMBTRIG_DISABLE )
#define PWM_USER_CMBTRIG_CTA4EN		( PWM_DRV_CMBTRIG_DISABLE )
#define PWM_USER_CMBTRIG_CTA5EN		( PWM_DRV_CMBTRIG_DISABLE )
#define PWM_USER_CMBTRIG_CTA6EN		( PWM_DRV_CMBTRIG_DISABLE )
#define PWM_USER_CMBTRIG_CTA7EN		( PWM_DRV_CMBTRIG_DISABLE )
#define PWM_USER_CMBTRIG_CTA8EN		( PWM_DRV_CMBTRIG_DISABLE )

#define PWM_USER_CMBTRIG_CTB1EN		( PWM_DRV_CMBTRIG_DISABLE )
#define PWM_USER_CMBTRIG_CTB2EN		( PWM_DRV_CMBTRIG_DISABLE )
#define PWM_USER_CMBTRIG_CTB3EN		( PWM_DRV_CMBTRIG_DISABLE )
#define PWM_USER_CMBTRIG_CTB4EN		( PWM_DRV_CMBTRIG_DISABLE )
#define PWM_USER_CMBTRIG_CTB5EN		( PWM_DRV_CMBTRIG_DISABLE )
#define PWM_USER_CMBTRIG_CTB6EN		( PWM_DRV_CMBTRIG_DISABLE )
#define PWM_USER_CMBTRIG_CTB7EN		( PWM_DRV_CMBTRIG_DISABLE )
#define PWM_USER_CMBTRIG_CTB8EN		( PWM_DRV_CMBTRIG_DISABLE )

/*----------------------------------------------------------------------------*/
/* LOGCONy */
/*----------------------------------------------------------------------------*/
#define PWM_USER_LOGCONA_PWMLFAD	( PWM_DRV_LOGCON_DISTINATION_DISABLE )
#define PWM_USER_LOGCONA_PWMLFA  	( PWM_DRV_LOGCON_FUNCTION_OR)
#define PWM_USER_LOGCONA_S2APOL  	( PWM_DRV_LOGCON_SOURCE_POL_NORMAL )
#define PWM_USER_LOGCONA_S1APOL  	( PWM_DRV_LOGCON_SOURCE_POL_NORMAL )
#define PWM_USER_LOGCONA_PWMS2A  	( PWM_DRV_LOGCON_SOURCE_PWM1H )
#define PWM_USER_LOGCONA_PWMS1A  	( PWM_DRV_LOGCON_SOURCE_PWM1H )

#define PWM_USER_LOGCONB_PWMLFBD	( PWM_DRV_LOGCON_DISTINATION_DISABLE )
#define PWM_USER_LOGCONB_PWMLFB  	( PWM_DRV_LOGCON_FUNCTION_OR)
#define PWM_USER_LOGCONB_S2BPOL  	( PWM_DRV_LOGCON_SOURCE_POL_NORMAL )
#define PWM_USER_LOGCONB_S1BPOL  	( PWM_DRV_LOGCON_SOURCE_POL_NORMAL )
#define PWM_USER_LOGCONB_PWMS2B  	( PWM_DRV_LOGCON_SOURCE_PWM1H )
#define PWM_USER_LOGCONB_PWMS1B  	( PWM_DRV_LOGCON_SOURCE_PWM1H )

#define PWM_USER_LOGCONC_PWMLFCD	( PWM_DRV_LOGCON_DISTINATION_DISABLE )
#define PWM_USER_LOGCONC_PWMLFC  	( PWM_DRV_LOGCON_FUNCTION_OR)
#define PWM_USER_LOGCONC_S2CPOL  	( PWM_DRV_LOGCON_SOURCE_POL_NORMAL )
#define PWM_USER_LOGCONC_S1CPOL  	( PWM_DRV_LOGCON_SOURCE_POL_NORMAL )
#define PWM_USER_LOGCONC_PWMS2C  	( PWM_DRV_LOGCON_SOURCE_PWM1H )
#define PWM_USER_LOGCONC_PWMS1C  	( PWM_DRV_LOGCON_SOURCE_PWM1H )

#define PWM_USER_LOGCOND_PWMLFDD	( PWM_DRV_LOGCON_DISTINATION_DISABLE )
#define PWM_USER_LOGCOND_PWMLFD  	( PWM_DRV_LOGCON_FUNCTION_OR)
#define PWM_USER_LOGCOND_S2DPOL  	( PWM_DRV_LOGCON_SOURCE_POL_NORMAL )
#define PWM_USER_LOGCOND_S1DPOL  	( PWM_DRV_LOGCON_SOURCE_POL_NORMAL )
#define PWM_USER_LOGCOND_PWMS2D  	( PWM_DRV_LOGCON_SOURCE_PWM1H )
#define PWM_USER_LOGCOND_PWMS1D  	( PWM_DRV_LOGCON_SOURCE_PWM1H )

#define PWM_USER_LOGCONE_PWMLFED	( PWM_DRV_LOGCON_DISTINATION_DISABLE )
#define PWM_USER_LOGCONE_PWMLFE  	( PWM_DRV_LOGCON_FUNCTION_OR)
#define PWM_USER_LOGCONE_S2EPOL  	( PWM_DRV_LOGCON_SOURCE_POL_NORMAL )
#define PWM_USER_LOGCONE_S1EPOL  	( PWM_DRV_LOGCON_SOURCE_POL_NORMAL )
#define PWM_USER_LOGCONE_PWMS2E  	( PWM_DRV_LOGCON_SOURCE_PWM1H )
#define PWM_USER_LOGCONE_PWMS1E  	( PWM_DRV_LOGCON_SOURCE_PWM1H )

#define PWM_USER_LOGCONF_PWMLFFD	( PWM_DRV_LOGCON_DISTINATION_DISABLE )
#define PWM_USER_LOGCONF_PWMLFF  	( PWM_DRV_LOGCON_FUNCTION_OR)
#define PWM_USER_LOGCONF_S2FPOL  	( PWM_DRV_LOGCON_SOURCE_POL_NORMAL )
#define PWM_USER_LOGCONF_S1FPOL  	( PWM_DRV_LOGCON_SOURCE_POL_NORMAL )
#define PWM_USER_LOGCONF_PWMS2F  	( PWM_DRV_LOGCON_SOURCE_PWM1H )
#define PWM_USER_LOGCONF_PWMS1F  	( PWM_DRV_LOGCON_SOURCE_PWM1H )

/*----------------------------------------------------------------------------*/
/* PWMEVTy */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PWMEVTA_EVTAPGS	( PWM_DRV_PWMEVT_EVTSEL_PWM1 )
#define PWM_USER_PWMEVTA_EVTASEL  	( PWM_DRV_PWMEVT_EVTSEL_PGTRGSEL)
#define PWM_USER_PWMEVTA_EVTASYNC  	( PWM_DRV_PWMEVT_EVTSYNC_OFF )
#define PWM_USER_PWMEVTA_EVTASTRD  	( PWM_DRV_PWMEVT_EVTSTRD_8CLOCK )
#define PWM_USER_PWMEVTA_EVTAPOL 	( PWM_DRV_PWMEVT_EVTPOL_ACTIVE_H )
#define PWM_USER_PWMEVTA_EVTAOEN  	( PWM_DRV_PWMEVT_EVTOEN_DISABLE )

#define PWM_USER_PWMEVTB_EVTBPGS	( PWM_DRV_PWMEVT_EVTSEL_PWM1 )
#define PWM_USER_PWMEVTB_EVTBSEL  	( PWM_DRV_PWMEVT_EVTSEL_PGTRGSEL)
#define PWM_USER_PWMEVTB_EVTBSYNC  	( PWM_DRV_PWMEVT_EVTSYNC_OFF )
#define PWM_USER_PWMEVTB_EVTBSTRD  	( PWM_DRV_PWMEVT_EVTSTRD_8CLOCK )
#define PWM_USER_PWMEVTB_EVTBPOL 	( PWM_DRV_PWMEVT_EVTPOL_ACTIVE_H )
#define PWM_USER_PWMEVTB_EVTBOEN  	( PWM_DRV_PWMEVT_EVTOEN_DISABLE )

#define PWM_USER_PWMEVTC_EVTCPGS	( PWM_DRV_PWMEVT_EVTSEL_PWM1 )
#define PWM_USER_PWMEVTC_EVTCSEL  	( PWM_DRV_PWMEVT_EVTSEL_PGTRGSEL)
#define PWM_USER_PWMEVTC_EVTCSYNC  	( PWM_DRV_PWMEVT_EVTSYNC_OFF )
#define PWM_USER_PWMEVTC_EVTCSTRD  	( PWM_DRV_PWMEVT_EVTSTRD_8CLOCK )
#define PWM_USER_PWMEVTC_EVTCPOL 	( PWM_DRV_PWMEVT_EVTPOL_ACTIVE_H )
#define PWM_USER_PWMEVTC_EVTCOEN  	( PWM_DRV_PWMEVT_EVTOEN_DISABLE )

#define PWM_USER_PWMEVTD_EVTDPGS	( PWM_DRV_PWMEVT_EVTSEL_PWM1 )
#define PWM_USER_PWMEVTD_EVTDSEL  	( PWM_DRV_PWMEVT_EVTSEL_PGTRGSEL)
#define PWM_USER_PWMEVTD_EVTDSYNC  	( PWM_DRV_PWMEVT_EVTSYNC_OFF )
#define PWM_USER_PWMEVTD_EVTDSTRD  	( PWM_DRV_PWMEVT_EVTSTRD_8CLOCK )
#define PWM_USER_PWMEVTD_EVTDPOL 	( PWM_DRV_PWMEVT_EVTPOL_ACTIVE_H )
#define PWM_USER_PWMEVTD_EVTDOEN  	( PWM_DRV_PWMEVT_EVTOEN_DISABLE )

#define PWM_USER_PWMEVTE_EVTEPGS	( PWM_DRV_PWMEVT_EVTSEL_PWM1 )
#define PWM_USER_PWMEVTE_EVTESEL  	( PWM_DRV_PWMEVT_EVTSEL_PGTRGSEL)
#define PWM_USER_PWMEVTE_EVTESYNC  	( PWM_DRV_PWMEVT_EVTSYNC_OFF )
#define PWM_USER_PWMEVTE_EVTESTRD  	( PWM_DRV_PWMEVT_EVTSTRD_8CLOCK )
#define PWM_USER_PWMEVTE_EVTEPOL 	( PWM_DRV_PWMEVT_EVTPOL_ACTIVE_H )
#define PWM_USER_PWMEVTE_EVTEOEN  	( PWM_DRV_PWMEVT_EVTOEN_DISABLE )

#define PWM_USER_PWMEVTF_EVTFPGS	( PWM_DRV_PWMEVT_EVTSEL_PWM1 )
#define PWM_USER_PWMEVTF_EVTFSEL  	( PWM_DRV_PWMEVT_EVTSEL_PGTRGSEL)
#define PWM_USER_PWMEVTF_EVTFSYNC  	( PWM_DRV_PWMEVT_EVTSYNC_OFF )
#define PWM_USER_PWMEVTF_EVTFSTRD  	( PWM_DRV_PWMEVT_EVTSTRD_8CLOCK )
#define PWM_USER_PWMEVTF_EVTFPOL 	( PWM_DRV_PWMEVT_EVTPOL_ACTIVE_H )
#define PWM_USER_PWMEVTF_EVTFOEN  	( PWM_DRV_PWMEVT_EVTOEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG1CON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG1CON_MODSEL		( PWM_DRV_PGCON_MODSEL_INDEPENDENT_EDGE )
#define PWM_USER_PG1CON_CLKSEL		( PWM_DRV_PGCON_CLKSEL_MCLKSEL )
#define PWM_USER_PG1CON_TRGCNT		( PWM_DRV_PGCON_TRGCNT_1CYCLE)
#define PWM_USER_PG1CON_ON			( PWM_DRV_PGCON_ON_ENABLE )
#define PWM_USER_PG1CON_SOCS		( PWM_DRV_PGCON_SOCS_LOCAL_EOC )
#define PWM_USER_PG1CON_TRGMOD		( PWM_DRV_PGCON_TRGMOD_SINGLE_TRIGGER )
#define PWM_USER_PG1CON_UPDMOD		( PWM_DRV_PGCON_UPDMOD_SOC )
#define PWM_USER_PG1CON_MSTEN		( PWM_DRV_PGCON_MSTEN_DISABLE )
#define PWM_USER_PG1CON_MPHSEL		( PWM_DRV_PGCON_MPHSEL_PGPHASE )
#define PWM_USER_PG1CON_MPERSEL		( PWM_DRV_PGCON_MPERSEL_PGPER )
#define PWM_USER_PG1CON_MDCSEL		( PWM_DRV_PGCON_MDCSEL_PGDC )

/*----------------------------------------------------------------------------*/
/* PG1IOCON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG1IOCON_DBDAT		( PWM_DRV_PGIOCON_DBDAT_HL_LL )
#define PWM_USER_PG1IOCON_FFDAT		( PWM_DRV_PGIOCON_FFDAT_HL_LL )
#define PWM_USER_PG1IOCON_CLDAT		( PWM_DRV_PGIOCON_CLDAT_HL_LL )
#define PWM_USER_PG1IOCON_FLTDAT	( PWM_DRV_PGIOCON_FLTDAT_HL_LL )
#define PWM_USER_PG1IOCON_OSYNC		( PWM_DRV_PGIOCON_OSYNC_TIMEBASE )
#define PWM_USER_PG1IOCON_OVRDAT	( PWM_DRV_PGIOCON_OVRDAT_HL_LL )
#define PWM_USER_PG1IOCON_OVRENL	( PWM_DRV_PGIOCON_OVRENL_DISABLE )
#define PWM_USER_PG1IOCON_OVRENH	( PWM_DRV_PGIOCON_OVRENH_DISABLE )
#define PWM_USER_PG1IOCON_SWAP		( PWM_DRV_PGIOCON_SWAP_DISABLE )
#define PWM_USER_PG1IOCON_CLMOD		( PWM_DRV_PGIOCON_CLMOD_CLDAT)
#define PWM_USER_PG1IOCON_POLL		( PWM_DRV_PGIOCON_POLL_ACTIVE_HIGH )
#define PWM_USER_PG1IOCON_POLH		( PWM_DRV_PGIOCON_POLH_ACTIVE_HIGH )
#define PWM_USER_PG1IOCON_PENL		( PWM_DRV_PGIOCON_PENL_DISABLE )
#define PWM_USER_PG1IOCON_PENH		( PWM_DRV_PGIOCON_PENH_DISABLE )
#define PWM_USER_PG1IOCON_PMOD		( PWM_DRV_PGIOCON_PMOD_COMPLEMENTARY )
#define PWM_USER_PG1IOCON_DTCMPSEL	( PWM_DRV_PGIOCON_DTCMPSEL_PCI_SYNC )
#define PWM_USER_PG1IOCON_PPSEN		( PWM_DRV_PGIOCON_PPSEN_DISABLE )
#define PWM_USER_PG1IOCON_CAPSRC	( PWM_DRV_PGIOCON_CAPSRC_SOFTWARE )

/*----------------------------------------------------------------------------*/
/* PG1EVT */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG1EVT_PGTRGSEL	( PWM_DRV_PGEVT_PGTRGSEL_EOC )
#define PWM_USER_PG1EVT_UPDTRG		( PWM_DRV_PGEVT_UPDTRG_MANUAL )
#define PWM_USER_PG1EVT_PWMPCI		( PWM_DRV_PGEVT_PWMPCI_PWMGEN1 )
#define PWM_USER_PG1EVT_ADTR1EN1	( PWM_DRV_PGEVT_ADTR1EN1_DISABLE )
#define PWM_USER_PG1EVT_ADTR1EN2	( PWM_DRV_PGEVT_ADTR1EN2_DISABLE)
#define PWM_USER_PG1EVT_ADTR1EN3	( PWM_DRV_PGEVT_ADTR1EN3_DISABLE )
#define PWM_USER_PG1EVT_ADTR1PS		( 0u )
#define PWM_USER_PG1EVT_ADTR1OFS	( PWM_DRV_PGEVT_ADTR1OFS_NO_OFFSET )
#define PWM_USER_PG1EVT_ADTR2EN1	( PWM_DRV_PGEVT_ADTR2EN1_DISABLE)
#define PWM_USER_PG1EVT_ADTR2EN2	( PWM_DRV_PGEVT_ADTR2EN2_DISABLE )
#define PWM_USER_PG1EVT_ADTR2EN3	( PWM_DRV_PGEVT_ADTR2EN3_DISABLE )
#define PWM_USER_PG1EVT_IEVTSEL		( PWM_DRV_PGEVT_IEVTSEL_EOC )
#define PWM_USER_PG1EVT_SIEN		( PWM_DRV_PGEVT_SIEN_DISABLE)
#define PWM_USER_PG1EVT_FFIEN		( PWM_DRV_PGEVT_FFIEN_DISABLE )
#define PWM_USER_PG1EVT_CLIEN		( PWM_DRV_PGEVT_CLIEN_DISABLE )
#define PWM_USER_PG1EVT_FLTIEN		( PWM_DRV_PGEVT_FLTIEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG1FPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG1FPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG1FPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG1FPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG1FPCI_SWTERM		( 0u )
#define PWM_USER_PG1FPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG1FPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG1FPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG1FPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG1FPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG1FPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG1FPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG1FPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG1FPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG1FPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG1FPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG1FPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG1FPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG1CLPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG1CLPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG1CLPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG1CLPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG1CLPCI_SWTERM	( 0u )
#define PWM_USER_PG1CLPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG1CLPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG1CLPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG1CLPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG1CLPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG1CLPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG1CLPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG1CLPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG1CLPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG1CLPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG1CLPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG1CLPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG1CLPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG1FFPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG1FFPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG1FFPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG1FFPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG1FFPCI_SWTERM	( 0u )
#define PWM_USER_PG1FFPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG1FFPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG1FFPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG1FFPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG1FFPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG1FFPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG1FFPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG1FFPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG1FFPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG1FFPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG1FFPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG1FFPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG1FFPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG1SPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG1SPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG1SPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG1SPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG1SPCI_SWTERM		( 0u )
#define PWM_USER_PG1SPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG1SPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG1SPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG1SPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG1SPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG1SPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG1SPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG1SPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG1SPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG1SPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG1SPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG1SPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG1SPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG1LEB */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG1LEB_LEB			( 0u )
#define PWM_USER_PG1LEB_PLF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG1LEB_PLR			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG1LEB_PHF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG1LEB_PHR			( PWM_DRV_PGLEB_DISABLE )

/*----------------------------------------------------------------------------*/
/* OTHER */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG1PHASE			( 0u )	//位相
#define PWM_USER_PG1DC				( 0u )	//Duty
#define PWM_USER_PG1DCA				( 0u )	//Duty補償
#define PWM_USER_PG1PER				( 0u )	//周期

#define PWM_USER_PG1TRIGA_TRIGA		( 0u )
#define PWM_USER_PG1TRIGA_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG1TRIGB_TRIGB		( 0u )
#define PWM_USER_PG1TRIGB_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG1TRIGC_TRIGC		( 0u )
#define PWM_USER_PG1TRIGC_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG1DC_DTL			( 0u )	//デッドタイムLow
#define PWM_USER_PG1DC_DTH			( 0u )	//デッドタイムHigh


/*----------------------------------------------------------------------------*/
/* PG2CON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG2CON_MODSEL		( PWM_DRV_PGCON_MODSEL_INDEPENDENT_EDGE )
#define PWM_USER_PG2CON_CLKSEL		( PWM_DRV_PGCON_CLKSEL_MCLKSEL )
#define PWM_USER_PG2CON_TRGCNT		( PWM_DRV_PGCON_TRGCNT_1CYCLE)
#define PWM_USER_PG2CON_ON			( PWM_DRV_PGCON_ON_ENABLE )
#define PWM_USER_PG2CON_SOCS		( PWM_DRV_PGCON_SOCS_LOCAL_EOC )
#define PWM_USER_PG2CON_TRGMOD		( PWM_DRV_PGCON_TRGMOD_SINGLE_TRIGGER )
#define PWM_USER_PG2CON_UPDMOD		( PWM_DRV_PGCON_UPDMOD_SOC )
#define PWM_USER_PG2CON_MSTEN		( PWM_DRV_PGCON_MSTEN_DISABLE )
#define PWM_USER_PG2CON_MPHSEL		( PWM_DRV_PGCON_MPHSEL_PGPHASE )
#define PWM_USER_PG2CON_MPERSEL		( PWM_DRV_PGCON_MPERSEL_PGPER )
#define PWM_USER_PG2CON_MDCSEL		( PWM_DRV_PGCON_MDCSEL_PGDC )

/*----------------------------------------------------------------------------*/
/* PG2IOCON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG2IOCON_DBDAT		( PWM_DRV_PGIOCON_DBDAT_HL_LL )
#define PWM_USER_PG2IOCON_FFDAT		( PWM_DRV_PGIOCON_FFDAT_HL_LL )
#define PWM_USER_PG2IOCON_CLDAT		( PWM_DRV_PGIOCON_CLDAT_HL_LL )
#define PWM_USER_PG2IOCON_FLTDAT	( PWM_DRV_PGIOCON_FLTDAT_HL_LL )
#define PWM_USER_PG2IOCON_OSYNC		( PWM_DRV_PGIOCON_OSYNC_TIMEBASE )
#define PWM_USER_PG2IOCON_OVRDAT	( PWM_DRV_PGIOCON_OVRDAT_HL_LL )
#define PWM_USER_PG2IOCON_OVRENL	( PWM_DRV_PGIOCON_OVRENL_DISABLE )
#define PWM_USER_PG2IOCON_OVRENH	( PWM_DRV_PGIOCON_OVRENH_DISABLE )
#define PWM_USER_PG2IOCON_SWAP		( PWM_DRV_PGIOCON_SWAP_DISABLE )
#define PWM_USER_PG2IOCON_CLMOD		( PWM_DRV_PGIOCON_CLMOD_CLDAT)
#define PWM_USER_PG2IOCON_POLL		( PWM_DRV_PGIOCON_POLL_ACTIVE_HIGH )
#define PWM_USER_PG2IOCON_POLH		( PWM_DRV_PGIOCON_POLH_ACTIVE_HIGH )
#define PWM_USER_PG2IOCON_PENL		( PWM_DRV_PGIOCON_PENL_DISABLE )
#define PWM_USER_PG2IOCON_PENH		( PWM_DRV_PGIOCON_PENH_DISABLE )
#define PWM_USER_PG2IOCON_PMOD		( PWM_DRV_PGIOCON_PMOD_COMPLEMENTARY )
#define PWM_USER_PG2IOCON_DTCMPSEL	( PWM_DRV_PGIOCON_DTCMPSEL_PCI_SYNC )
#define PWM_USER_PG2IOCON_PPSEN		( PWM_DRV_PGIOCON_PPSEN_DISABLE )
#define PWM_USER_PG2IOCON_CAPSRC	( PWM_DRV_PGIOCON_CAPSRC_SOFTWARE )

/*----------------------------------------------------------------------------*/
/* PG2EVT */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG2EVT_PGTRGSEL	( PWM_DRV_PGEVT_PGTRGSEL_EOC )
#define PWM_USER_PG2EVT_UPDTRG		( PWM_DRV_PGEVT_UPDTRG_MANUAL )
#define PWM_USER_PG2EVT_PWMPCI		( PWM_DRV_PGEVT_PWMPCI_PWMGEN1 )
#define PWM_USER_PG2EVT_ADTR1EN1	( PWM_DRV_PGEVT_ADTR1EN1_DISABLE )
#define PWM_USER_PG2EVT_ADTR1EN2	( PWM_DRV_PGEVT_ADTR1EN2_DISABLE)
#define PWM_USER_PG2EVT_ADTR1EN3	( PWM_DRV_PGEVT_ADTR1EN3_DISABLE )
#define PWM_USER_PG2EVT_ADTR1PS		( 0u )
#define PWM_USER_PG2EVT_ADTR1OFS	( PWM_DRV_PGEVT_ADTR1OFS_NO_OFFSET )
#define PWM_USER_PG2EVT_ADTR2EN1	( PWM_DRV_PGEVT_ADTR2EN1_DISABLE)
#define PWM_USER_PG2EVT_ADTR2EN2	( PWM_DRV_PGEVT_ADTR2EN2_DISABLE )
#define PWM_USER_PG2EVT_ADTR2EN3	( PWM_DRV_PGEVT_ADTR2EN3_DISABLE )
#define PWM_USER_PG2EVT_IEVTSEL		( PWM_DRV_PGEVT_IEVTSEL_EOC )
#define PWM_USER_PG2EVT_SIEN		( PWM_DRV_PGEVT_SIEN_DISABLE)
#define PWM_USER_PG2EVT_FFIEN		( PWM_DRV_PGEVT_FFIEN_DISABLE )
#define PWM_USER_PG2EVT_CLIEN		( PWM_DRV_PGEVT_CLIEN_DISABLE )
#define PWM_USER_PG2EVT_FLTIEN		( PWM_DRV_PGEVT_FLTIEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG2FPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG2FPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG2FPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG2FPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG2FPCI_SWTERM		( 0u )
#define PWM_USER_PG2FPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG2FPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG2FPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG2FPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG2FPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG2FPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG2FPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG2FPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG2FPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG2FPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG2FPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG2FPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG2FPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG2CLPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG2CLPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG2CLPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG2CLPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG2CLPCI_SWTERM	( 0u )
#define PWM_USER_PG2CLPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG2CLPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG2CLPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG2CLPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG2CLPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG2CLPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG2CLPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG2CLPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG2CLPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG2CLPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG2CLPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG2CLPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG2CLPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG2FFPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG2FFPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG2FFPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG2FFPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG2FFPCI_SWTERM	( 0u )
#define PWM_USER_PG2FFPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG2FFPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG2FFPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG2FFPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG2FFPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG2FFPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG2FFPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG2FFPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG2FFPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG2FFPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG2FFPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG2FFPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG2FFPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG2SPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG2SPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG2SPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG2SPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG2SPCI_SWTERM		( 0u )
#define PWM_USER_PG2SPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG2SPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG2SPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG2SPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG2SPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG2SPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG2SPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG2SPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG2SPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG2SPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG2SPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG2SPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG2SPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG2LEB */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG2LEB_LEB			( 0u )
#define PWM_USER_PG2LEB_PLF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG2LEB_PLR			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG2LEB_PHF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG2LEB_PHR			( PWM_DRV_PGLEB_DISABLE )

/*----------------------------------------------------------------------------*/
/* OTHER */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG2PHASE			( 0u )	//位相
#define PWM_USER_PG2DC				( 0u )	//Duty
#define PWM_USER_PG2DCA				( 0u )	//Duty補償
#define PWM_USER_PG2PER				( 0u )	//周期

#define PWM_USER_PG2TRIGA_TRIGA		( 0u )
#define PWM_USER_PG2TRIGA_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG2TRIGB_TRIGB		( 0u )
#define PWM_USER_PG2TRIGB_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG2TRIGC_TRIGC		( 0u )
#define PWM_USER_PG2TRIGC_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG2DC_DTL			( 0u )	//デッドタイムLow
#define PWM_USER_PG2DC_DTH			( 0u )	//デッドタイムHigh

/*----------------------------------------------------------------------------*/
/* PG3CON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG3CON_MODSEL		( PWM_DRV_PGCON_MODSEL_INDEPENDENT_EDGE )
#define PWM_USER_PG3CON_CLKSEL		( PWM_DRV_PGCON_CLKSEL_MCLKSEL )
#define PWM_USER_PG3CON_TRGCNT		( PWM_DRV_PGCON_TRGCNT_1CYCLE)
#define PWM_USER_PG3CON_ON			( PWM_DRV_PGCON_ON_ENABLE )
#define PWM_USER_PG3CON_SOCS		( PWM_DRV_PGCON_SOCS_LOCAL_EOC )
#define PWM_USER_PG3CON_TRGMOD		( PWM_DRV_PGCON_TRGMOD_SINGLE_TRIGGER )
#define PWM_USER_PG3CON_UPDMOD		( PWM_DRV_PGCON_UPDMOD_SOC )
#define PWM_USER_PG3CON_MSTEN		( PWM_DRV_PGCON_MSTEN_DISABLE )
#define PWM_USER_PG3CON_MPHSEL		( PWM_DRV_PGCON_MPHSEL_PGPHASE )
#define PWM_USER_PG3CON_MPERSEL		( PWM_DRV_PGCON_MPERSEL_PGPER )
#define PWM_USER_PG3CON_MDCSEL		( PWM_DRV_PGCON_MDCSEL_PGDC )

/*----------------------------------------------------------------------------*/
/* PG3IOCON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG3IOCON_DBDAT		( PWM_DRV_PGIOCON_DBDAT_HL_LL )
#define PWM_USER_PG3IOCON_FFDAT		( PWM_DRV_PGIOCON_FFDAT_HL_LL )
#define PWM_USER_PG3IOCON_CLDAT		( PWM_DRV_PGIOCON_CLDAT_HL_LL )
#define PWM_USER_PG3IOCON_FLTDAT	( PWM_DRV_PGIOCON_FLTDAT_HL_LL )
#define PWM_USER_PG3IOCON_OSYNC		( PWM_DRV_PGIOCON_OSYNC_TIMEBASE )
#define PWM_USER_PG3IOCON_OVRDAT	( PWM_DRV_PGIOCON_OVRDAT_HL_LL )
#define PWM_USER_PG3IOCON_OVRENL	( PWM_DRV_PGIOCON_OVRENL_DISABLE )
#define PWM_USER_PG3IOCON_OVRENH	( PWM_DRV_PGIOCON_OVRENH_DISABLE )
#define PWM_USER_PG3IOCON_SWAP		( PWM_DRV_PGIOCON_SWAP_DISABLE )
#define PWM_USER_PG3IOCON_CLMOD		( PWM_DRV_PGIOCON_CLMOD_CLDAT)
#define PWM_USER_PG3IOCON_POLL		( PWM_DRV_PGIOCON_POLL_ACTIVE_HIGH )
#define PWM_USER_PG3IOCON_POLH		( PWM_DRV_PGIOCON_POLH_ACTIVE_HIGH )
#define PWM_USER_PG3IOCON_PENL		( PWM_DRV_PGIOCON_PENL_DISABLE )
#define PWM_USER_PG3IOCON_PENH		( PWM_DRV_PGIOCON_PENH_DISABLE )
#define PWM_USER_PG3IOCON_PMOD		( PWM_DRV_PGIOCON_PMOD_COMPLEMENTARY )
#define PWM_USER_PG3IOCON_DTCMPSEL	( PWM_DRV_PGIOCON_DTCMPSEL_PCI_SYNC )
#define PWM_USER_PG3IOCON_PPSEN		( PWM_DRV_PGIOCON_PPSEN_DISABLE )
#define PWM_USER_PG3IOCON_CAPSRC	( PWM_DRV_PGIOCON_CAPSRC_SOFTWARE )

/*----------------------------------------------------------------------------*/
/* PG3EVT */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG3EVT_PGTRGSEL	( PWM_DRV_PGEVT_PGTRGSEL_EOC )
#define PWM_USER_PG3EVT_UPDTRG		( PWM_DRV_PGEVT_UPDTRG_MANUAL )
#define PWM_USER_PG3EVT_PWMPCI		( PWM_DRV_PGEVT_PWMPCI_PWMGEN1 )
#define PWM_USER_PG3EVT_ADTR1EN1	( PWM_DRV_PGEVT_ADTR1EN1_DISABLE )
#define PWM_USER_PG3EVT_ADTR1EN2	( PWM_DRV_PGEVT_ADTR1EN2_DISABLE)
#define PWM_USER_PG3EVT_ADTR1EN3	( PWM_DRV_PGEVT_ADTR1EN3_DISABLE )
#define PWM_USER_PG3EVT_ADTR1PS		( 0u )
#define PWM_USER_PG3EVT_ADTR1OFS	( PWM_DRV_PGEVT_ADTR1OFS_NO_OFFSET )
#define PWM_USER_PG3EVT_ADTR2EN1	( PWM_DRV_PGEVT_ADTR2EN1_DISABLE)
#define PWM_USER_PG3EVT_ADTR2EN2	( PWM_DRV_PGEVT_ADTR2EN2_DISABLE )
#define PWM_USER_PG3EVT_ADTR2EN3	( PWM_DRV_PGEVT_ADTR2EN3_DISABLE )
#define PWM_USER_PG3EVT_IEVTSEL		( PWM_DRV_PGEVT_IEVTSEL_EOC )
#define PWM_USER_PG3EVT_SIEN		( PWM_DRV_PGEVT_SIEN_DISABLE)
#define PWM_USER_PG3EVT_FFIEN		( PWM_DRV_PGEVT_FFIEN_DISABLE )
#define PWM_USER_PG3EVT_CLIEN		( PWM_DRV_PGEVT_CLIEN_DISABLE )
#define PWM_USER_PG3EVT_FLTIEN		( PWM_DRV_PGEVT_FLTIEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG3FPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG3FPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG3FPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG3FPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG3FPCI_SWTERM		( 0u )
#define PWM_USER_PG3FPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG3FPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG3FPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG3FPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG3FPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG3FPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG3FPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG3FPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG3FPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG3FPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG3FPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG3FPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG3FPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG3CLPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG3CLPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG3CLPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG3CLPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG3CLPCI_SWTERM	( 0u )
#define PWM_USER_PG3CLPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG3CLPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG3CLPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG3CLPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG3CLPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG3CLPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG3CLPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG3CLPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG3CLPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG3CLPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG3CLPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG3CLPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG3CLPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG3FFPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG3FFPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG3FFPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG3FFPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG3FFPCI_SWTERM	( 0u )
#define PWM_USER_PG3FFPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG3FFPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG3FFPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG3FFPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG3FFPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG3FFPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG3FFPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG3FFPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG3FFPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG3FFPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG3FFPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG3FFPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG3FFPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG3SPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG3SPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG3SPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG3SPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG3SPCI_SWTERM		( 0u )
#define PWM_USER_PG3SPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG3SPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG3SPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG3SPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG3SPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG3SPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG3SPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG3SPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG3SPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG3SPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG3SPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG3SPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG3SPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG3LEB*/
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG3LEB_LEB			( 0u )
#define PWM_USER_PG3LEB_PLF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG3LEB_PLR			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG3LEB_PHF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG3LEB_PHR			( PWM_DRV_PGLEB_DISABLE )

/*----------------------------------------------------------------------------*/
/* OTHER */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG3PHASE			( 0u )	//位相
#define PWM_USER_PG3DC				( 0u )	//Duty
#define PWM_USER_PG3DCA				( 0u )	//Duty補償
#define PWM_USER_PG3PER				( 0u )	//周期

#define PWM_USER_PG3TRIGA_TRIGA		( 0u )
#define PWM_USER_PG3TRIGA_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG3TRIGB_TRIGB		( 0u )
#define PWM_USER_PG3TRIGB_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG3TRIGC_TRIGC		( 0u )
#define PWM_USER_PG3TRIGC_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG3DC_DTL			( 0u )	//デッドタイムLow
#define PWM_USER_PG3DC_DTH			( 0u )	//デッドタイムHigh

/*----------------------------------------------------------------------------*/
/* PG4CON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG4CON_MODSEL		( PWM_DRV_PGCON_MODSEL_INDEPENDENT_EDGE )
#define PWM_USER_PG4CON_CLKSEL		( PWM_DRV_PGCON_CLKSEL_MCLKSEL )
#define PWM_USER_PG4CON_TRGCNT		( PWM_DRV_PGCON_TRGCNT_1CYCLE)
#define PWM_USER_PG4CON_ON			( PWM_DRV_PGCON_ON_ENABLE )
#define PWM_USER_PG4CON_SOCS		( PWM_DRV_PGCON_SOCS_LOCAL_EOC )
#define PWM_USER_PG4CON_TRGMOD		( PWM_DRV_PGCON_TRGMOD_SINGLE_TRIGGER )
#define PWM_USER_PG4CON_UPDMOD		( PWM_DRV_PGCON_UPDMOD_SOC )
#define PWM_USER_PG4CON_MSTEN		( PWM_DRV_PGCON_MSTEN_DISABLE )
#define PWM_USER_PG4CON_MPHSEL		( PWM_DRV_PGCON_MPHSEL_PGPHASE )
#define PWM_USER_PG4CON_MPERSEL		( PWM_DRV_PGCON_MPERSEL_PGPER )
#define PWM_USER_PG4CON_MDCSEL		( PWM_DRV_PGCON_MDCSEL_PGDC )

/*----------------------------------------------------------------------------*/
/* PG4IOCON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG4IOCON_DBDAT		( PWM_DRV_PGIOCON_DBDAT_HL_LL )
#define PWM_USER_PG4IOCON_FFDAT		( PWM_DRV_PGIOCON_FFDAT_HL_LL )
#define PWM_USER_PG4IOCON_CLDAT		( PWM_DRV_PGIOCON_CLDAT_HL_LL )
#define PWM_USER_PG4IOCON_FLTDAT	( PWM_DRV_PGIOCON_FLTDAT_HL_LL )
#define PWM_USER_PG4IOCON_OSYNC		( PWM_DRV_PGIOCON_OSYNC_TIMEBASE )
#define PWM_USER_PG4IOCON_OVRDAT	( PWM_DRV_PGIOCON_OVRDAT_HL_LL )
#define PWM_USER_PG4IOCON_OVRENL	( PWM_DRV_PGIOCON_OVRENL_DISABLE )
#define PWM_USER_PG4IOCON_OVRENH	( PWM_DRV_PGIOCON_OVRENH_DISABLE )
#define PWM_USER_PG4IOCON_SWAP		( PWM_DRV_PGIOCON_SWAP_DISABLE )
#define PWM_USER_PG4IOCON_CLMOD		( PWM_DRV_PGIOCON_CLMOD_CLDAT)
#define PWM_USER_PG4IOCON_POLL		( PWM_DRV_PGIOCON_POLL_ACTIVE_HIGH )
#define PWM_USER_PG4IOCON_POLH		( PWM_DRV_PGIOCON_POLH_ACTIVE_HIGH )
#define PWM_USER_PG4IOCON_PENL		( PWM_DRV_PGIOCON_PENL_DISABLE )
#define PWM_USER_PG4IOCON_PENH		( PWM_DRV_PGIOCON_PENH_DISABLE )
#define PWM_USER_PG4IOCON_PMOD		( PWM_DRV_PGIOCON_PMOD_COMPLEMENTARY )
#define PWM_USER_PG4IOCON_DTCMPSEL	( PWM_DRV_PGIOCON_DTCMPSEL_PCI_SYNC )
#define PWM_USER_PG4IOCON_PPSEN		( PWM_DRV_PGIOCON_PPSEN_DISABLE )
#define PWM_USER_PG4IOCON_CAPSRC	( PWM_DRV_PGIOCON_CAPSRC_SOFTWARE )

/*----------------------------------------------------------------------------*/
/* PG4EVT */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG4EVT_PGTRGSEL	( PWM_DRV_PGEVT_PGTRGSEL_EOC )
#define PWM_USER_PG4EVT_UPDTRG		( PWM_DRV_PGEVT_UPDTRG_MANUAL )
#define PWM_USER_PG4EVT_PWMPCI		( PWM_DRV_PGEVT_PWMPCI_PWMGEN1 )
#define PWM_USER_PG4EVT_ADTR1EN1	( PWM_DRV_PGEVT_ADTR1EN1_DISABLE )
#define PWM_USER_PG4EVT_ADTR1EN2	( PWM_DRV_PGEVT_ADTR1EN2_DISABLE)
#define PWM_USER_PG4EVT_ADTR1EN3	( PWM_DRV_PGEVT_ADTR1EN3_DISABLE )
#define PWM_USER_PG4EVT_ADTR1PS		( 0u )
#define PWM_USER_PG4EVT_ADTR1OFS	( PWM_DRV_PGEVT_ADTR1OFS_NO_OFFSET )
#define PWM_USER_PG4EVT_ADTR2EN1	( PWM_DRV_PGEVT_ADTR2EN1_DISABLE)
#define PWM_USER_PG4EVT_ADTR2EN2	( PWM_DRV_PGEVT_ADTR2EN2_DISABLE )
#define PWM_USER_PG4EVT_ADTR2EN3	( PWM_DRV_PGEVT_ADTR2EN3_DISABLE )
#define PWM_USER_PG4EVT_IEVTSEL		( PWM_DRV_PGEVT_IEVTSEL_EOC )
#define PWM_USER_PG4EVT_SIEN		( PWM_DRV_PGEVT_SIEN_DISABLE)
#define PWM_USER_PG4EVT_FFIEN		( PWM_DRV_PGEVT_FFIEN_DISABLE )
#define PWM_USER_PG4EVT_CLIEN		( PWM_DRV_PGEVT_CLIEN_DISABLE )
#define PWM_USER_PG4EVT_FLTIEN		( PWM_DRV_PGEVT_FLTIEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG4FPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG4FPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG4FPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG4FPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG4FPCI_SWTERM		( 0u )
#define PWM_USER_PG4FPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG4FPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG4FPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG4FPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG4FPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG4FPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG4FPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG4FPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG4FPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG4FPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG4FPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG4FPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG4FPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG4CLPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG4CLPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG4CLPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG4CLPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG4CLPCI_SWTERM	( 0u )
#define PWM_USER_PG4CLPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG4CLPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG4CLPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG4CLPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG4CLPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG4CLPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG4CLPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG4CLPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG4CLPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG4CLPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG4CLPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG4CLPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG4CLPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG4FFPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG4FFPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG4FFPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG4FFPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG4FFPCI_SWTERM	( 0u )
#define PWM_USER_PG4FFPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG4FFPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG4FFPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG4FFPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG4FFPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG4FFPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG4FFPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG4FFPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG4FFPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG4FFPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG4FFPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG4FFPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG4FFPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG4SPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG4SPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG4SPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG4SPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG4SPCI_SWTERM		( 0u )
#define PWM_USER_PG4SPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG4SPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG4SPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG4SPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG4SPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG4SPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG4SPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG4SPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG4SPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG4SPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG4SPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG4SPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG4SPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG4LEB */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG4LEB_LEB			( 0u )
#define PWM_USER_PG4LEB_PLF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG4LEB_PLR			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG4LEB_PHF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG4LEB_PHR			( PWM_DRV_PGLEB_DISABLE )

/*----------------------------------------------------------------------------*/
/* OTHER */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG4PHASE			( 0u )	//位相
#define PWM_USER_PG4DC				( 0u )	//Duty
#define PWM_USER_PG4DCA				( 0u )	//Duty補償
#define PWM_USER_PG4PER				( 0u )	//周期

#define PWM_USER_PG4TRIGA_TRIGA		( 0u )
#define PWM_USER_PG4TRIGA_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG4TRIGB_TRIGB		( 0u )
#define PWM_USER_PG4TRIGB_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG4TRIGC_TRIGC		( 0u )
#define PWM_USER_PG4TRIGC_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG4DC_DTL			( 0u )	//デッドタイムLow
#define PWM_USER_PG4DC_DTH			( 0u )	//デッドタイムHigh

/*----------------------------------------------------------------------------*/
/* PG5CON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG5CON_MODSEL		( PWM_DRV_PGCON_MODSEL_INDEPENDENT_EDGE )
#define PWM_USER_PG5CON_CLKSEL		( PWM_DRV_PGCON_CLKSEL_MCLKSEL )
#define PWM_USER_PG5CON_TRGCNT		( PWM_DRV_PGCON_TRGCNT_1CYCLE)
#define PWM_USER_PG5CON_ON			( PWM_DRV_PGCON_ON_ENABLE )
#define PWM_USER_PG5CON_SOCS		( PWM_DRV_PGCON_SOCS_LOCAL_EOC )
#define PWM_USER_PG5CON_TRGMOD		( PWM_DRV_PGCON_TRGMOD_SINGLE_TRIGGER )
#define PWM_USER_PG5CON_UPDMOD		( PWM_DRV_PGCON_UPDMOD_SOC )
#define PWM_USER_PG5CON_MSTEN		( PWM_DRV_PGCON_MSTEN_DISABLE )
#define PWM_USER_PG5CON_MPHSEL		( PWM_DRV_PGCON_MPHSEL_PGPHASE )
#define PWM_USER_PG5CON_MPERSEL		( PWM_DRV_PGCON_MPERSEL_PGPER )
#define PWM_USER_PG5CON_MDCSEL		( PWM_DRV_PGCON_MDCSEL_PGDC )

/*----------------------------------------------------------------------------*/
/* PG5IOCON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG5IOCON_DBDAT		( PWM_DRV_PGIOCON_DBDAT_HL_LL )
#define PWM_USER_PG5IOCON_FFDAT		( PWM_DRV_PGIOCON_FFDAT_HL_LL )
#define PWM_USER_PG5IOCON_CLDAT		( PWM_DRV_PGIOCON_CLDAT_HL_LL )
#define PWM_USER_PG5IOCON_FLTDAT	( PWM_DRV_PGIOCON_FLTDAT_HL_LL )
#define PWM_USER_PG5IOCON_OSYNC		( PWM_DRV_PGIOCON_OSYNC_TIMEBASE )
#define PWM_USER_PG5IOCON_OVRDAT	( PWM_DRV_PGIOCON_OVRDAT_HL_LL )
#define PWM_USER_PG5IOCON_OVRENL	( PWM_DRV_PGIOCON_OVRENL_DISABLE )
#define PWM_USER_PG5IOCON_OVRENH	( PWM_DRV_PGIOCON_OVRENH_DISABLE )
#define PWM_USER_PG5IOCON_SWAP		( PWM_DRV_PGIOCON_SWAP_DISABLE )
#define PWM_USER_PG5IOCON_CLMOD		( PWM_DRV_PGIOCON_CLMOD_CLDAT)
#define PWM_USER_PG5IOCON_POLL		( PWM_DRV_PGIOCON_POLL_ACTIVE_HIGH )
#define PWM_USER_PG5IOCON_POLH		( PWM_DRV_PGIOCON_POLH_ACTIVE_HIGH )
#define PWM_USER_PG5IOCON_PENL		( PWM_DRV_PGIOCON_PENL_DISABLE )
#define PWM_USER_PG5IOCON_PENH		( PWM_DRV_PGIOCON_PENH_DISABLE )
#define PWM_USER_PG5IOCON_PMOD		( PWM_DRV_PGIOCON_PMOD_COMPLEMENTARY )
#define PWM_USER_PG5IOCON_DTCMPSEL	( PWM_DRV_PGIOCON_DTCMPSEL_PCI_SYNC )
#define PWM_USER_PG5IOCON_PPSEN		( PWM_DRV_PGIOCON_PPSEN_DISABLE )
#define PWM_USER_PG5IOCON_CAPSRC	( PWM_DRV_PGIOCON_CAPSRC_SOFTWARE )

/*----------------------------------------------------------------------------*/
/* PG5EVT */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG5EVT_PGTRGSEL	( PWM_DRV_PGEVT_PGTRGSEL_EOC )
#define PWM_USER_PG5EVT_UPDTRG		( PWM_DRV_PGEVT_UPDTRG_MANUAL )
#define PWM_USER_PG5EVT_PWMPCI		( PWM_DRV_PGEVT_PWMPCI_PWMGEN1 )
#define PWM_USER_PG5EVT_ADTR1EN1	( PWM_DRV_PGEVT_ADTR1EN1_DISABLE )
#define PWM_USER_PG5EVT_ADTR1EN2	( PWM_DRV_PGEVT_ADTR1EN2_DISABLE)
#define PWM_USER_PG5EVT_ADTR1EN3	( PWM_DRV_PGEVT_ADTR1EN3_DISABLE )
#define PWM_USER_PG5EVT_ADTR1PS		( 0u )
#define PWM_USER_PG5EVT_ADTR1OFS	( PWM_DRV_PGEVT_ADTR1OFS_NO_OFFSET )
#define PWM_USER_PG5EVT_ADTR2EN1	( PWM_DRV_PGEVT_ADTR2EN1_DISABLE)
#define PWM_USER_PG5EVT_ADTR2EN2	( PWM_DRV_PGEVT_ADTR2EN2_DISABLE )
#define PWM_USER_PG5EVT_ADTR2EN3	( PWM_DRV_PGEVT_ADTR2EN3_DISABLE )
#define PWM_USER_PG5EVT_IEVTSEL		( PWM_DRV_PGEVT_IEVTSEL_EOC )
#define PWM_USER_PG5EVT_SIEN		( PWM_DRV_PGEVT_SIEN_DISABLE)
#define PWM_USER_PG5EVT_FFIEN		( PWM_DRV_PGEVT_FFIEN_DISABLE )
#define PWM_USER_PG5EVT_CLIEN		( PWM_DRV_PGEVT_CLIEN_DISABLE )
#define PWM_USER_PG5EVT_FLTIEN		( PWM_DRV_PGEVT_FLTIEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG5FPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG5FPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG5FPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG5FPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG5FPCI_SWTERM		( 0u )
#define PWM_USER_PG5FPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG5FPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG5FPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG5FPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG5FPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG5FPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG5FPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG5FPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG5FPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG5FPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG5FPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG5FPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG5FPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG5CLPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG5CLPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG5CLPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG5CLPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG5CLPCI_SWTERM	( 0u )
#define PWM_USER_PG5CLPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG5CLPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG5CLPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG5CLPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG5CLPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG5CLPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG5CLPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG5CLPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG5CLPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG5CLPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG5CLPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG5CLPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG5CLPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG5FFPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG5FFPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG5FFPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG5FFPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG5FFPCI_SWTERM	( 0u )
#define PWM_USER_PG5FFPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG5FFPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG5FFPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG5FFPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG5FFPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG5FFPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG5FFPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG5FFPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG5FFPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG5FFPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG5FFPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG5FFPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG5FFPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG5SPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG5SPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG5SPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG5SPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG5SPCI_SWTERM		( 0u )
#define PWM_USER_PG5SPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG5SPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG5SPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG5SPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG5SPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG5SPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG5SPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG5SPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG5SPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG5SPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG5SPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG5SPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG5SPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG5LEB */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG5LEB_LEB			( 0u )
#define PWM_USER_PG5LEB_PLF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG5LEB_PLR			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG5LEB_PHF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG5LEB_PHR			( PWM_DRV_PGLEB_DISABLE )

/*----------------------------------------------------------------------------*/
/* OTHER */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG5PHASE			( 0u )	//位相
#define PWM_USER_PG5DC				( 0u )	//Duty
#define PWM_USER_PG5DCA				( 0u )	//Duty補償
#define PWM_USER_PG5PER				( 0u )	//周期

#define PWM_USER_PG5TRIGA_TRIGA		( 0u )
#define PWM_USER_PG5TRIGA_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG5TRIGB_TRIGB		( 0u )
#define PWM_USER_PG5TRIGB_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG5TRIGC_TRIGC		( 0u )
#define PWM_USER_PG5TRIGC_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG5DC_DTL			( 0u )	//デッドタイムLow
#define PWM_USER_PG5DC_DTH			( 0u )	//デッドタイムHigh

/*----------------------------------------------------------------------------*/
/* PG6CON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG6CON_MODSEL		( PWM_DRV_PGCON_MODSEL_INDEPENDENT_EDGE )
#define PWM_USER_PG6CON_CLKSEL		( PWM_DRV_PGCON_CLKSEL_MCLKSEL )
#define PWM_USER_PG6CON_TRGCNT		( PWM_DRV_PGCON_TRGCNT_1CYCLE)
#define PWM_USER_PG6CON_ON			( PWM_DRV_PGCON_ON_ENABLE )
#define PWM_USER_PG6CON_SOCS		( PWM_DRV_PGCON_SOCS_LOCAL_EOC )
#define PWM_USER_PG6CON_TRGMOD		( PWM_DRV_PGCON_TRGMOD_SINGLE_TRIGGER )
#define PWM_USER_PG6CON_UPDMOD		( PWM_DRV_PGCON_UPDMOD_SOC )
#define PWM_USER_PG6CON_MSTEN		( PWM_DRV_PGCON_MSTEN_DISABLE )
#define PWM_USER_PG6CON_MPHSEL		( PWM_DRV_PGCON_MPHSEL_PGPHASE )
#define PWM_USER_PG6CON_MPERSEL		( PWM_DRV_PGCON_MPERSEL_PGPER )
#define PWM_USER_PG6CON_MDCSEL		( PWM_DRV_PGCON_MDCSEL_PGDC )

/*----------------------------------------------------------------------------*/
/* PG6IOCON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG6IOCON_DBDAT		( PWM_DRV_PGIOCON_DBDAT_HL_LL )
#define PWM_USER_PG6IOCON_FFDAT		( PWM_DRV_PGIOCON_FFDAT_HL_LL )
#define PWM_USER_PG6IOCON_CLDAT		( PWM_DRV_PGIOCON_CLDAT_HL_LL )
#define PWM_USER_PG6IOCON_FLTDAT	( PWM_DRV_PGIOCON_FLTDAT_HL_LL )
#define PWM_USER_PG6IOCON_OSYNC		( PWM_DRV_PGIOCON_OSYNC_TIMEBASE )
#define PWM_USER_PG6IOCON_OVRDAT	( PWM_DRV_PGIOCON_OVRDAT_HL_LL )
#define PWM_USER_PG6IOCON_OVRENL	( PWM_DRV_PGIOCON_OVRENL_DISABLE )
#define PWM_USER_PG6IOCON_OVRENH	( PWM_DRV_PGIOCON_OVRENH_DISABLE )
#define PWM_USER_PG6IOCON_SWAP		( PWM_DRV_PGIOCON_SWAP_DISABLE )
#define PWM_USER_PG6IOCON_CLMOD		( PWM_DRV_PGIOCON_CLMOD_CLDAT)
#define PWM_USER_PG6IOCON_POLL		( PWM_DRV_PGIOCON_POLL_ACTIVE_HIGH )
#define PWM_USER_PG6IOCON_POLH		( PWM_DRV_PGIOCON_POLH_ACTIVE_HIGH )
#define PWM_USER_PG6IOCON_PENL		( PWM_DRV_PGIOCON_PENL_DISABLE )
#define PWM_USER_PG6IOCON_PENH		( PWM_DRV_PGIOCON_PENH_DISABLE )
#define PWM_USER_PG6IOCON_PMOD		( PWM_DRV_PGIOCON_PMOD_COMPLEMENTARY )
#define PWM_USER_PG6IOCON_DTCMPSEL	( PWM_DRV_PGIOCON_DTCMPSEL_PCI_SYNC )
#define PWM_USER_PG6IOCON_PPSEN		( PWM_DRV_PGIOCON_PPSEN_DISABLE )
#define PWM_USER_PG6IOCON_CAPSRC	( PWM_DRV_PGIOCON_CAPSRC_SOFTWARE )

/*----------------------------------------------------------------------------*/
/* PG6EVT */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG6EVT_PGTRGSEL	( PWM_DRV_PGEVT_PGTRGSEL_EOC )
#define PWM_USER_PG6EVT_UPDTRG		( PWM_DRV_PGEVT_UPDTRG_MANUAL )
#define PWM_USER_PG6EVT_PWMPCI		( PWM_DRV_PGEVT_PWMPCI_PWMGEN1 )
#define PWM_USER_PG6EVT_ADTR1EN1	( PWM_DRV_PGEVT_ADTR1EN1_DISABLE )
#define PWM_USER_PG6EVT_ADTR1EN2	( PWM_DRV_PGEVT_ADTR1EN2_DISABLE)
#define PWM_USER_PG6EVT_ADTR1EN3	( PWM_DRV_PGEVT_ADTR1EN3_DISABLE )
#define PWM_USER_PG6EVT_ADTR1PS		( 0u )
#define PWM_USER_PG6EVT_ADTR1OFS	( PWM_DRV_PGEVT_ADTR1OFS_NO_OFFSET )
#define PWM_USER_PG6EVT_ADTR2EN1	( PWM_DRV_PGEVT_ADTR2EN1_DISABLE)
#define PWM_USER_PG6EVT_ADTR2EN2	( PWM_DRV_PGEVT_ADTR2EN2_DISABLE )
#define PWM_USER_PG6EVT_ADTR2EN3	( PWM_DRV_PGEVT_ADTR2EN3_DISABLE )
#define PWM_USER_PG6EVT_IEVTSEL		( PWM_DRV_PGEVT_IEVTSEL_EOC )
#define PWM_USER_PG6EVT_SIEN		( PWM_DRV_PGEVT_SIEN_DISABLE)
#define PWM_USER_PG6EVT_FFIEN		( PWM_DRV_PGEVT_FFIEN_DISABLE )
#define PWM_USER_PG6EVT_CLIEN		( PWM_DRV_PGEVT_CLIEN_DISABLE )
#define PWM_USER_PG6EVT_FLTIEN		( PWM_DRV_PGEVT_FLTIEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG6FPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG6FPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG6FPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG6FPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG6FPCI_SWTERM		( 0u )
#define PWM_USER_PG6FPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG6FPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG6FPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG6FPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG6FPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG6FPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG6FPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG6FPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG6FPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG6FPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG6FPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG6FPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG6FPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG6CLPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG6CLPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG6CLPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG6CLPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG6CLPCI_SWTERM	( 0u )
#define PWM_USER_PG6CLPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG6CLPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG6CLPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG6CLPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG6CLPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG6CLPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG6CLPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG6CLPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG6CLPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG6CLPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG6CLPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG6CLPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG6CLPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG6FFPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG6FFPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG6FFPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG6FFPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG6FFPCI_SWTERM	( 0u )
#define PWM_USER_PG6FFPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG6FFPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG6FFPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG6FFPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG6FFPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG6FFPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG6FFPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG6FFPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG6FFPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG6FFPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG6FFPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG6FFPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG6FFPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG6SPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG6SPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG6SPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG6SPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG6SPCI_SWTERM		( 0u )
#define PWM_USER_PG6SPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG6SPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG6SPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG6SPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG6SPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG6SPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG6SPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG6SPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG6SPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG6SPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG6SPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG6SPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG6SPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG6LEB */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG6LEB_LEB			( 0u )
#define PWM_USER_PG6LEB_PLF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG6LEB_PLR			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG6LEB_PHF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG6LEB_PHR			( PWM_DRV_PGLEB_DISABLE )

/*----------------------------------------------------------------------------*/
/* OTHER */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG6PHASE			( 0u )	//位相
#define PWM_USER_PG6DC				( 0u )	//Duty
#define PWM_USER_PG6DCA				( 0u )	//Duty補償
#define PWM_USER_PG6PER				( 0u )	//周期

#define PWM_USER_PG6TRIGA_TRIGA		( 0u )
#define PWM_USER_PG6TRIGA_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG6TRIGB_TRIGB		( 0u )
#define PWM_USER_PG6TRIGB_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG6TRIGC_TRIGC		( 0u )
#define PWM_USER_PG6TRIGC_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG6DC_DTL			( 0u )	//デッドタイムLow
#define PWM_USER_PG6DC_DTH			( 0u )	//デッドタイムHigh

/*----------------------------------------------------------------------------*/
/* PG7CON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG7CON_MODSEL		( PWM_DRV_PGCON_MODSEL_INDEPENDENT_EDGE )
#define PWM_USER_PG7CON_CLKSEL		( PWM_DRV_PGCON_CLKSEL_MCLKSEL )
#define PWM_USER_PG7CON_TRGCNT		( PWM_DRV_PGCON_TRGCNT_1CYCLE)
#define PWM_USER_PG7CON_ON			( PWM_DRV_PGCON_ON_ENABLE )
#define PWM_USER_PG7CON_SOCS		( PWM_DRV_PGCON_SOCS_LOCAL_EOC )
#define PWM_USER_PG7CON_TRGMOD		( PWM_DRV_PGCON_TRGMOD_SINGLE_TRIGGER )
#define PWM_USER_PG7CON_UPDMOD		( PWM_DRV_PGCON_UPDMOD_SOC )
#define PWM_USER_PG7CON_MSTEN		( PWM_DRV_PGCON_MSTEN_DISABLE )
#define PWM_USER_PG7CON_MPHSEL		( PWM_DRV_PGCON_MPHSEL_PGPHASE )
#define PWM_USER_PG7CON_MPERSEL		( PWM_DRV_PGCON_MPERSEL_PGPER )
#define PWM_USER_PG7CON_MDCSEL		( PWM_DRV_PGCON_MDCSEL_PGDC )

/*----------------------------------------------------------------------------*/
/* PG7IOCON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG7IOCON_DBDAT		( PWM_DRV_PGIOCON_DBDAT_HL_LL )
#define PWM_USER_PG7IOCON_FFDAT		( PWM_DRV_PGIOCON_FFDAT_HL_LL )
#define PWM_USER_PG7IOCON_CLDAT		( PWM_DRV_PGIOCON_CLDAT_HL_LL )
#define PWM_USER_PG7IOCON_FLTDAT	( PWM_DRV_PGIOCON_FLTDAT_HL_LL )
#define PWM_USER_PG7IOCON_OSYNC		( PWM_DRV_PGIOCON_OSYNC_TIMEBASE )
#define PWM_USER_PG7IOCON_OVRDAT	( PWM_DRV_PGIOCON_OVRDAT_HL_LL )
#define PWM_USER_PG7IOCON_OVRENL	( PWM_DRV_PGIOCON_OVRENL_DISABLE )
#define PWM_USER_PG7IOCON_OVRENH	( PWM_DRV_PGIOCON_OVRENH_DISABLE )
#define PWM_USER_PG7IOCON_SWAP		( PWM_DRV_PGIOCON_SWAP_DISABLE )
#define PWM_USER_PG7IOCON_CLMOD		( PWM_DRV_PGIOCON_CLMOD_CLDAT)
#define PWM_USER_PG7IOCON_POLL		( PWM_DRV_PGIOCON_POLL_ACTIVE_HIGH )
#define PWM_USER_PG7IOCON_POLH		( PWM_DRV_PGIOCON_POLH_ACTIVE_HIGH )
#define PWM_USER_PG7IOCON_PENL		( PWM_DRV_PGIOCON_PENL_DISABLE )
#define PWM_USER_PG7IOCON_PENH		( PWM_DRV_PGIOCON_PENH_DISABLE )
#define PWM_USER_PG7IOCON_PMOD		( PWM_DRV_PGIOCON_PMOD_COMPLEMENTARY )
#define PWM_USER_PG7IOCON_DTCMPSEL	( PWM_DRV_PGIOCON_DTCMPSEL_PCI_SYNC )
#define PWM_USER_PG7IOCON_PPSEN		( PWM_DRV_PGIOCON_PPSEN_DISABLE )
#define PWM_USER_PG7IOCON_CAPSRC	( PWM_DRV_PGIOCON_CAPSRC_SOFTWARE )

/*----------------------------------------------------------------------------*/
/* PG7EVT */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG7EVT_PGTRGSEL	( PWM_DRV_PGEVT_PGTRGSEL_EOC )
#define PWM_USER_PG7EVT_UPDTRG		( PWM_DRV_PGEVT_UPDTRG_MANUAL )
#define PWM_USER_PG7EVT_PWMPCI		( PWM_DRV_PGEVT_PWMPCI_PWMGEN1 )
#define PWM_USER_PG7EVT_ADTR1EN1	( PWM_DRV_PGEVT_ADTR1EN1_DISABLE )
#define PWM_USER_PG7EVT_ADTR1EN2	( PWM_DRV_PGEVT_ADTR1EN2_DISABLE)
#define PWM_USER_PG7EVT_ADTR1EN3	( PWM_DRV_PGEVT_ADTR1EN3_DISABLE )
#define PWM_USER_PG7EVT_ADTR1PS		( 0u )
#define PWM_USER_PG7EVT_ADTR1OFS	( PWM_DRV_PGEVT_ADTR1OFS_NO_OFFSET )
#define PWM_USER_PG7EVT_ADTR2EN1	( PWM_DRV_PGEVT_ADTR2EN1_DISABLE)
#define PWM_USER_PG7EVT_ADTR2EN2	( PWM_DRV_PGEVT_ADTR2EN2_DISABLE )
#define PWM_USER_PG7EVT_ADTR2EN3	( PWM_DRV_PGEVT_ADTR2EN3_DISABLE )
#define PWM_USER_PG7EVT_IEVTSEL		( PWM_DRV_PGEVT_IEVTSEL_EOC )
#define PWM_USER_PG7EVT_SIEN		( PWM_DRV_PGEVT_SIEN_DISABLE)
#define PWM_USER_PG7EVT_FFIEN		( PWM_DRV_PGEVT_FFIEN_DISABLE )
#define PWM_USER_PG7EVT_CLIEN		( PWM_DRV_PGEVT_CLIEN_DISABLE )
#define PWM_USER_PG7EVT_FLTIEN		( PWM_DRV_PGEVT_FLTIEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG7FPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG7FPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG7FPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG7FPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG7FPCI_SWTERM		( 0u )
#define PWM_USER_PG7FPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG7FPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG7FPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG7FPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG7FPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG7FPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG7FPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG7FPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG7FPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG7FPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG7FPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG7FPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG7FPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG7CLPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG7CLPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG7CLPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG7CLPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG7CLPCI_SWTERM	( 0u )
#define PWM_USER_PG7CLPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG7CLPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG7CLPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG7CLPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG7CLPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG7CLPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG7CLPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG7CLPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG7CLPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG7CLPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG7CLPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG7CLPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG7CLPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG7FFPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG7FFPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG7FFPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG7FFPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG7FFPCI_SWTERM	( 0u )
#define PWM_USER_PG7FFPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG7FFPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG7FFPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG7FFPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG7FFPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG7FFPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG7FFPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG7FFPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG7FFPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG7FFPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG7FFPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG7FFPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG7FFPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG7SPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG7SPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG7SPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG7SPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG7SPCI_SWTERM		( 0u )
#define PWM_USER_PG7SPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG7SPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG7SPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG7SPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG7SPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG7SPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG7SPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG7SPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG7SPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG7SPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG7SPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG7SPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG7SPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG7LEB */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG7LEB_LEB			( 0u )
#define PWM_USER_PG7LEB_PLF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG7LEB_PLR			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG7LEB_PHF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG7LEB_PHR			( PWM_DRV_PGLEB_DISABLE )

/*----------------------------------------------------------------------------*/
/* OTHER */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG7PHASE			( 0u )	//位相
#define PWM_USER_PG7DC				( 0u )	//Duty
#define PWM_USER_PG7DCA				( 0u )	//Duty補償
#define PWM_USER_PG7PER				( 0u )	//周期

#define PWM_USER_PG7TRIGA_TRIGA		( 0u )
#define PWM_USER_PG7TRIGA_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG7TRIGB_TRIGB		( 0u )
#define PWM_USER_PG7TRIGB_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG7TRIGC_TRIGC		( 0u )
#define PWM_USER_PG7TRIGC_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG7DC_DTL			( 0u )	//デッドタイムLow
#define PWM_USER_PG7DC_DTH			( 0u )	//デッドタイムHigh

/*----------------------------------------------------------------------------*/
/* PG8CON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG8CON_MODSEL		( PWM_DRV_PGCON_MODSEL_INDEPENDENT_EDGE )
#define PWM_USER_PG8CON_CLKSEL		( PWM_DRV_PGCON_CLKSEL_MCLKSEL )
#define PWM_USER_PG8CON_TRGCNT		( PWM_DRV_PGCON_TRGCNT_1CYCLE)
#define PWM_USER_PG8CON_ON			( PWM_DRV_PGCON_ON_ENABLE )
#define PWM_USER_PG8CON_SOCS		( PWM_DRV_PGCON_SOCS_LOCAL_EOC )
#define PWM_USER_PG8CON_TRGMOD		( PWM_DRV_PGCON_TRGMOD_SINGLE_TRIGGER )
#define PWM_USER_PG8CON_UPDMOD		( PWM_DRV_PGCON_UPDMOD_SOC )
#define PWM_USER_PG8CON_MSTEN		( PWM_DRV_PGCON_MSTEN_DISABLE )
#define PWM_USER_PG8CON_MPHSEL		( PWM_DRV_PGCON_MPHSEL_PGPHASE )
#define PWM_USER_PG8CON_MPERSEL		( PWM_DRV_PGCON_MPERSEL_PGPER )
#define PWM_USER_PG8CON_MDCSEL		( PWM_DRV_PGCON_MDCSEL_PGDC )

/*----------------------------------------------------------------------------*/
/* PG8IOCON */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG8IOCON_DBDAT		( PWM_DRV_PGIOCON_DBDAT_HL_LL )
#define PWM_USER_PG8IOCON_FFDAT		( PWM_DRV_PGIOCON_FFDAT_HL_LL )
#define PWM_USER_PG8IOCON_CLDAT		( PWM_DRV_PGIOCON_CLDAT_HL_LL )
#define PWM_USER_PG8IOCON_FLTDAT	( PWM_DRV_PGIOCON_FLTDAT_HL_LL )
#define PWM_USER_PG8IOCON_OSYNC		( PWM_DRV_PGIOCON_OSYNC_TIMEBASE )
#define PWM_USER_PG8IOCON_OVRDAT	( PWM_DRV_PGIOCON_OVRDAT_HL_LL )
#define PWM_USER_PG8IOCON_OVRENL	( PWM_DRV_PGIOCON_OVRENL_DISABLE )
#define PWM_USER_PG8IOCON_OVRENH	( PWM_DRV_PGIOCON_OVRENH_DISABLE )
#define PWM_USER_PG8IOCON_SWAP		( PWM_DRV_PGIOCON_SWAP_DISABLE )
#define PWM_USER_PG8IOCON_CLMOD		( PWM_DRV_PGIOCON_CLMOD_CLDAT)
#define PWM_USER_PG8IOCON_POLL		( PWM_DRV_PGIOCON_POLL_ACTIVE_HIGH )
#define PWM_USER_PG8IOCON_POLH		( PWM_DRV_PGIOCON_POLH_ACTIVE_HIGH )
#define PWM_USER_PG8IOCON_PENL		( PWM_DRV_PGIOCON_PENL_DISABLE )
#define PWM_USER_PG8IOCON_PENH		( PWM_DRV_PGIOCON_PENH_DISABLE )
#define PWM_USER_PG8IOCON_PMOD		( PWM_DRV_PGIOCON_PMOD_COMPLEMENTARY )
#define PWM_USER_PG8IOCON_DTCMPSEL	( PWM_DRV_PGIOCON_DTCMPSEL_PCI_SYNC )
#define PWM_USER_PG8IOCON_PPSEN		( PWM_DRV_PGIOCON_PPSEN_DISABLE )
#define PWM_USER_PG8IOCON_CAPSRC	( PWM_DRV_PGIOCON_CAPSRC_SOFTWARE )

/*----------------------------------------------------------------------------*/
/* PG8EVT */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG8EVT_PGTRGSEL	( PWM_DRV_PGEVT_PGTRGSEL_EOC )
#define PWM_USER_PG8EVT_UPDTRG		( PWM_DRV_PGEVT_UPDTRG_MANUAL )
#define PWM_USER_PG8EVT_PWMPCI		( PWM_DRV_PGEVT_PWMPCI_PWMGEN1 )
#define PWM_USER_PG8EVT_ADTR1EN1	( PWM_DRV_PGEVT_ADTR1EN1_DISABLE )
#define PWM_USER_PG8EVT_ADTR1EN2	( PWM_DRV_PGEVT_ADTR1EN2_DISABLE)
#define PWM_USER_PG8EVT_ADTR1EN3	( PWM_DRV_PGEVT_ADTR1EN3_DISABLE )
#define PWM_USER_PG8EVT_ADTR1PS		( 0u )
#define PWM_USER_PG8EVT_ADTR1OFS	( PWM_DRV_PGEVT_ADTR1OFS_NO_OFFSET )
#define PWM_USER_PG8EVT_ADTR2EN1	( PWM_DRV_PGEVT_ADTR2EN1_DISABLE)
#define PWM_USER_PG8EVT_ADTR2EN2	( PWM_DRV_PGEVT_ADTR2EN2_DISABLE )
#define PWM_USER_PG8EVT_ADTR2EN3	( PWM_DRV_PGEVT_ADTR2EN3_DISABLE )
#define PWM_USER_PG8EVT_IEVTSEL		( PWM_DRV_PGEVT_IEVTSEL_EOC )
#define PWM_USER_PG8EVT_SIEN		( PWM_DRV_PGEVT_SIEN_DISABLE)
#define PWM_USER_PG8EVT_FFIEN		( PWM_DRV_PGEVT_FFIEN_DISABLE )
#define PWM_USER_PG8EVT_CLIEN		( PWM_DRV_PGEVT_CLIEN_DISABLE )
#define PWM_USER_PG8EVT_FLTIEN		( PWM_DRV_PGEVT_FLTIEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG8FPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG8FPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG8FPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG8FPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG8FPCI_SWTERM		( 0u )
#define PWM_USER_PG8FPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG8FPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG8FPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG8FPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG8FPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG8FPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG8FPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG8FPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG8FPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG8FPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG8FPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG8FPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG8FPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG8CLPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG8CLPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG8CLPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG8CLPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG8CLPCI_SWTERM	( 0u )
#define PWM_USER_PG8CLPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG8CLPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG8CLPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG8CLPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG8CLPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG8CLPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG8CLPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG8CLPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG8CLPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG8CLPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG8CLPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG8CLPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG8CLPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG8FFPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG8FFPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG8FFPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG8FFPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG8FFPCI_SWTERM	( 0u )
#define PWM_USER_PG8FFPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG8FFPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG8FFPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG8FFPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG8FFPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG8FFPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG8FFPCI_LATMOD	( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG8FFPCI_SWPCIM	( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG8FFPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG8FFPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG8FFPCI_TERMPS	( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG8FFPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG8FFPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG8SPCI */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG8SPCI_PSS		( PWM_DRV_PGPCI_PSS_0)
#define PWM_USER_PG8SPCI_PPS		( PWM_DRV_PGPCI_PPS_NOT_INVERT)
#define PWM_USER_PG8SPCI_PSYNC		( PWM_DRV_PGPCI_PSYNC_NOT_PWM_EOC )
#define PWM_USER_PG8SPCI_SWTERM		( 0u )
#define PWM_USER_PG8SPCI_AQSS		( PWM_DRV_PGPCI_AQSS_1)
#define PWM_USER_PG8SPCI_AQPS		( PWM_DRV_PGPCI_AQPS_NOT_INVERT )
#define PWM_USER_PG8SPCI_TERM		( PWM_DRV_PGPCI_TERM_MANUAL )
#define PWM_USER_PG8SPCI_TSYNCDIS	( PWM_DRV_PGPCI_TSYNCDIS_PWM_EOC )
#define PWM_USER_PG8SPCI_TQSS		( PWM_DRV_PGPCI_TQSS_1)
#define PWM_USER_PG8SPCI_TQPS		( PWM_DRV_PGPCI_TQPS_NOT_INVERT )
#define PWM_USER_PG8SPCI_LATMOD		( PWM_DRV_PGPCI_LATMODE_SET_DOMI )
#define PWM_USER_PG8SPCI_SWPCIM		( PWM_DRV_PGPCI_SWPCIM_PCI_ACCPT )
#define PWM_USER_PG8SPCI_SWPCI		( PWM_DRV_PGPCI_SWPCI_DISABLE)
#define PWM_USER_PG8SPCI_ACP		( PWM_DRV_PGPCI_ACP_LEVEL )
#define PWM_USER_PG8SPCI_TERMPS		( PWM_DRV_PGPCI_TERMPS_NOT_INVERT )
#define PWM_USER_PG8SPCI_BPSEL		( PWM_DRV_PGPCI_BPSEL_PWM1 )
#define PWM_USER_PG8SPCI_BPEN		( PWM_DRV_PGPCI_BPEN_DISABLE )

/*----------------------------------------------------------------------------*/
/* PG8LEB */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG8LEB_LEB			( 0u )
#define PWM_USER_PG8LEB_PLF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG8LEB_PLR			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG8LEB_PHF			( PWM_DRV_PGLEB_DISABLE )
#define PWM_USER_PG8LEB_PHR			( PWM_DRV_PGLEB_DISABLE )

/*----------------------------------------------------------------------------*/
/* OTHER */
/*----------------------------------------------------------------------------*/
#define PWM_USER_PG8PHASE			( 0u )	//位相
#define PWM_USER_PG8DC				( 0u )	//Duty
#define PWM_USER_PG8DCA				( 0u )	//Duty補償
#define PWM_USER_PG8PER				( 0u )	//周期

#define PWM_USER_PG8TRIGA_TRIGA		( 0u )
#define PWM_USER_PG8TRIGA_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG8TRIGB_TRIGB		( 0u )
#define PWM_USER_PG8TRIGB_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG8TRIGC_TRIGC		( 0u )
#define PWM_USER_PG8TRIGC_CAHALF	( PWM_DRV_PGTRIG_FIRST )

#define PWM_USER_PG8DC_DTL			( 0u )	//デッドタイムLow
#define PWM_USER_PG8DC_DTH			( 0u )	//デッドタイムHigh
/*----------------------------------------------------------------------------*/
/*変数定義*/
/*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/
/*プロトタイプ宣言*/
/*----------------------------------------------------------------------------*/

#endif	/* PWM_USER_H */

